nixos:
    users:
        thelessone: ENC[AES256_GCM,data:2QJFoYAEmDIfcPSfGoIawZo70m/V0ZUwqQsk++ulYzaDm3UNia652ExO7Vw8LhXoi31o96vwXIZVSMayt9kKFhIvEQTayhQTxsqeitvjFVwZ15mY/TUTJU2Fx53PHXWtbUnD/FafhbzHBg==,iv:W+VWlK48zhb5f15GMQ2vm2s+KaNkb/PLXUDxP99xeyw=,tag:HjpdUn6qAUAL4zJJwSrGKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gezu4gq0a9s4fcmnjfjrc04f5y4748lddnufpt7qsq4t0cyq046qa2749t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa1JBdFJ0UmNuQ3FFTjRh
            M21nWGFoeDVVM1hxcEl2eWpmRVpKeWNjdEdJCmcvcy8rYjY3LzJETW5hZTM3Y1NV
            U21UZ0dLYmpIYzNDazhQNlVzd0ZUM2MKLS0tIHFPSmdXamNvclhUWWZWZFBMSlFa
            LzVIM0tJcU5VRzNUOWVFLzNTSHE3TEUK/2y4hcHOdqculOpX/AXuIUgDwEIZJiFr
            0blLE3+w+o4mihTg2CJc29YDQqFXz6qX0HXFyDHXiN+kgaILl/fx7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMWxLUUFyWWl3QmJpMWpM
            MHd4UGx6aEwrUGFNaWIwc3VqN3d0WWE0OWhFCnEyelR5Mmt4OC94bVB3ZjdsNUxu
            UWZBLzJNTUUxMFFzYnBwL25vNS9tb0EKLS0tIG13RmFkbDZLazdxSmt2MHkySkNr
            dVdxOXRMU0FEbWtTbTB3TFlGdEQ2VU0Kru5fHzvOaht4tGFIoYkwub32iaipws3E
            fsH/pO8M2y5AChPE1Kk6bVZaRb5IOKKC/BUt87up2a1+3pEavrvYJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T22:54:50Z"
    mac: ENC[AES256_GCM,data:jX2l4YvkRkOcELSzDX80fp9hVWi3oD8FglJtUuYztVTZCmD2rLzytIMO9kgzfznnZjes6O17CHeCGhQCVOXzJf6N2lJ8dr34G/1ZITknNmBA6us2pME0VkppA7QGsXdwfrIiX+LMTjcCNBPI9pSTp1xF2v5yUali3mgH6w5xzXM=,iv:4fDFWOGXatbTFKpmXOfuz8K5vkjy3WNctqHcfcZdZX8=,tag:CJBA2et/gF1C4gnUSBMvZA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
