[midnight-theme]
fetch.git = "https://github.com/refact0r/midnight-discord.git"
src.git = "https://github.com/refact0r/midnight-discord.git"

[openrgb]
fetch.git = "https://gitlab.com/CalcProgrammer1/OpenRGB.git"
src.git = "https://gitlab.com/CalcProgrammer1/OpenRGB.git"
pinned = true

[rofi-themes]
fetch.git = "https://github.com/adi1090x/rofi.git"
src.git = "https://github.com/adi1090x/rofi.git"

[suwayomi-server]
fetch.git = "https://github.com/Suwayomi/Suwayomi-Server.git"
src.git = "https://github.com/Suwayomi/Suwayomi-Server.git"

[suwayomi-webui]
fetch.git = "https://github.com/Suwayomi/Suwayomi-WebUI.git"
src.git = "https://github.com/Suwayomi/Suwayomi-WebUI.git"
