[midnight-theme]
fetch.git = "https://github.com/refact0r/midnight-discord.git"
src.git = "https://github.com/refact0r/midnight-discord.git"

[openrgb]
fetch.git = "https://gitlab.com/CalcProgrammer1/OpenRGB.git"
src.git = "https://gitlab.com/CalcProgrammer1/OpenRGB.git"
pinned = true

[rofi-themes]
fetch.git = "https://github.com/adi1090x/rofi.git"
src.git = "https://github.com/adi1090x/rofi.git"

[suwayomi-server]
fetch.git = "https://github.com/Suwayomi/Suwayomi-Server.git"
src.git = "https://github.com/Suwayomi/Suwayomi-Server.git"

[suwayomi-webui]
fetch.git = "https://github.com/Suwayomi/Suwayomi-WebUI.git"
src.git = "https://github.com/Suwayomi/Suwayomi-WebUI.git"

[lidarr]
fetch.url = "https://github.com/lidarr/Lidarr/releases/download/v$ver/Lidarr.master.$ver.linux-core-x64.tar.gz"
src.github_tag = "Lidarr/Lidarr"
src.prefix = "v"

[prowlarr]
fetch.url = "https://github.com/Prowlarr/Prowlarr/releases/download/v$ver/Prowlarr.master.$ver.linux-core-x64.tar.gz"
src.github_tag = "Prowlarr/Prowlarr"
src.prefix = "v"

[radarr]
fetch.url = "https://github.com/Radarr/Radarr/releases/download/v$ver/Radarr.master.$ver.linux-core-x64.tar.gz"
src.github_tag = "Radarr/Radarr"
src.prefix = "v"

[whisparr]
fetch.url = "https://whisparr.servarr.com/v1/update/eros/updatefile?version=$ver&os=linux&runtime=netcore&arch=x64"
url.name = "whisparr-src-$ver.tar.gz"
src.cmd = "curl -L 'https://whisparr.servarr.com/v1/update/eros/changes' --fail | jq -r '.[0].version'"

[osu-lazer-bin]
fetch.url = "https://github.com/ppy/osu/releases/download/$ver/osu.AppImage"
src.github_tag = "ppy/osu"
src.include_regex = "202\\d\\.\\d{1,4}\\.\\d"

[shoko-webui]
fetch.git = "https://github.com/ShokoAnime/Shoko-WebUI.git"
src.github_tag = "ShokoAnime/Shoko-WebUI"
