[__config__]
oldver = "pkgs/_versions/old_versions.json"
newver = "pkgs/_versions/new_versions.json"
keyfile = "/run/secrets/keys.toml"
max_concurrency = 3

["suwayomi-webui.revision"]
source = "httpheader"
url = "https://api.github.com/repos/Suwayomi/Suwayomi-WebUI/commits?sha=master&per_page=1&page=1"
header = "link"
regex = '(?<=page=)\d{2,5}'

["suwayomi-webui.yarnHash"]
source = "cmd"
cmd = '''
    yarnLock="$(mktemp /tmp/XXXXXX_yarn.lock)"

    curl -L \
        -H "Authorization: Bearer $(cat /run/secrets/githubToken)" \
        https://api.github.com/repos/Suwayomi/Suwayomi-WebUI/contents/yarn.lock \
        | jq -r .content \
        | base64 -d > $yarnLock

    nix hash convert --hash-algo sha256 --to sri $(prefetch-yarn-deps $yarnLock)

    rm $yarnLock
'''

["suwayomi-server.gradleDepsHash"]
source = "cmd"
cmd = '''
    updateScript="$(mktemp /tmp/XXXXXX_update_script.sh)"

    nix build .#suwayomi-server.mitmCache.updateScript --out-link $updateScript &> /dev/null
    $updateScript &> /dev/null
    
    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/suwayomi-server/deps.json | awk '{print $1}')

    rm $updateScript
'''
timeout = 300

["shoko-webui.pnpmHash"]
source = "cmd"
cmd = '''
    nix build .#shoko-webui --no-link | grep -oP "got\:.*\Ksha256.*"
'''
