[__config__]
oldver = "pkgs/_versions/old_versions.json"
newver = "pkgs/_versions/new_versions.json"
keyfile = "/run/secrets/keys.toml"
max_concurrency = 3

["suwayomi-webui.revision"]
source = "httpheader"
url = "https://api.github.com/repos/Suwayomi/Suwayomi-WebUI/commits?sha=master&per_page=1&page=1"
header = "link"
regex = '(?<=page=)\d{2,5}'

["suwayomi-webui.yarnHash"]
source = "cmd"
cmd = '''
    (nix build .#suwayomi-webui --no-link |& grep -oP "got\:.*\Ksha256.*") \
        || jq -r '.data."suwayomi-webui.yarnHash".version' pkgs/_versions/new_versions.json
'''

["suwayomi-server.gradleDepsHash"]
source = "cmd"
cmd = '''
    log="./update_suwayomi-server.gradleDepsHash.log"

    bash -c '
        set -xe

        outLink="$(mktemp ./XXXXXX_out_link -u)"
        updateScript="$(mktemp ./XXXXXX_update_script.sh -u)"

        echo "{}" > pkgs/suwayomi-server/deps.json

        nix build .#suwayomi-server.mitmCache.updateScript --out-link $outLink
        sed '\''s|/nix/store/[^/]*-source/pkgs/suwayomi-server/deps\.json|pkgs/suwayomi-server/deps.json|g'\'' \
            "$(readlink -f $outLink)" \
            > $updateScript
        sed '\''s|useBwrap="${USE_BWRAP:-1}"|useBwrap=""|g'\'' $updateScript \
            > $updateScript.tmp \
            && mv $updateScript.tmp $updateScript
        chmod +x $updateScript
        $updateScript

        rm $outLink $updateScript
    ' &> $log
    if [ -z $DEBUG_NVCHECKER ]; then rm $log; fi

    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/suwayomi-server/deps.json | awk '{print $1}')
'''

["shoko.nugetDepsHash"]
source = "cmd"
cmd = '''
    log="./update_shoko.nugetDepsHash.log"

    bash -c '
        set -xe

        outLink="$(mktemp ./XXXXXX_out_link -u)"
        updateScript="$(mktemp ./XXXXXX_update_script.sh -u)"

        nix build .#shoko.fetch-deps --out-link $outLink
        sed '\''s|/nix/store/[^/]*-source/pkgs/shoko/deps\.json|pkgs/shoko/deps.json|g'\'' \
            "$(readlink -f $outLink)" \
            > $updateScript
        chmod +x $updateScript
        $updateScript

        rm $outLink $updateScript
    ' &> $log
    if [ -z $DEBUG_NVCHECKER ]; then rm $log; fi

    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/shoko/deps.json | awk '{print $1}')
'''

["shokofin.nugetDepsHash"]
source = "cmd"
cmd = '''
    log="./update_shokofin.nugetDepsHash.log"

    bash -c '
        set -xe

        outLink="$(mktemp ./XXXXXX_out_link -u)"
        updateScript="$(mktemp ./XXXXXX_update_script.sh -u)"

        nix build .#shokofin.fetch-deps --out-link $outLink &>> $log
        sed 's|/nix/store/[^/]*-source/pkgs/shokofin/deps\.json|pkgs/shokofin/deps.json|g' \
            "$(readlink -f $outLink)" \
            > $updateScript
        chmod +x $updateScript &>> $log
        $updateScript

        rm $outLink $updateScript
    ' &> $log
    if [ -z $DEBUG_NVCHECKER ]; then rm $log; fi

    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/shokofin/deps.json | awk '{print $1}')
'''

["shoko-webui.pnpmHash"]
source = "cmd"
cmd = '''
    (nix build .#shoko-webui --no-link |& grep -oP "got\:.*\Ksha256.*") \
        || jq -r '.data."shoko-webui.pnpmHash".version' pkgs/_versions/new_versions.json
'''
