[__config__]
oldver = "pkgs/_versions/old_versions.json"
newver = "pkgs/_versions/new_versions.json"
keyfile = "/run/secrets/keys.toml"
max_concurrency = 3

["suwayomi-webui.revision"]
source = "httpheader"
url = "https://api.github.com/repos/Suwayomi/Suwayomi-WebUI/commits?sha=master&per_page=1&page=1"
header = "link"
regex = '(?<=page=)\d{2,5}'

["suwayomi-webui.yarnHash"]
source = "cmd"
cmd = '''
    yarnLock="$(mktemp ./XXXXXX_yarn.lock -u)"

    curl -L \
        -H "Authorization: Bearer $(cat $HOME/secrets/githubToken)" \
        https://api.github.com/repos/Suwayomi/Suwayomi-WebUI/contents/yarn.lock \
        | jq -r .content \
        | base64 -d > $yarnLock

    nix hash convert --hash-algo sha256 --to sri $(prefetch-yarn-deps $yarnLock)

    rm $yarnLock
'''

["suwayomi-server.gradleDepsHash"]
source = "cmd"
cmd = '''
    outLink="$(mktemp ./XXXXXX_out_link -u)"
    updateScript="$(mktemp ./XXXXXX_update_script.sh -u)"
    log="./update.log"

    echo "{}" > pkgs/suwayomi-server/deps.json

    nix build .#suwayomi-server.mitmCache.updateScript --out-link $outLink &>> $log
    sed 's|/nix/store/[^/]*-source/pkgs/suwayomi-server/deps\.json|pkgs/suwayomi-server/deps.json|g' \
        "$(readlink -f $outLink)" \
        > $updateScript
    chmod +x $updateScript &>> $log
    $updateScript &>> $log

    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/suwayomi-server/deps.json | awk '{print $1}')

    rm $outLink $updateScript
'''

["shoko.nugetDepsHash"]
source = "cmd"
cmd = '''
    outLink="$(mktemp ./XXXXXX_out_link -u)"
    updateScript="$(mktemp ./XXXXXX_update_script.sh -u)"
    log="./update.log"

    echo "{}" > pkgs/shoko/deps.json

    nix build .#shoko.fetch-deps --out-link $outLink &>> $log
    sed 's|/nix/store/[^/]*-source/pkgs/shoko/deps\.json|pkgs/shoko/deps.json|g' \
        "$(readlink -f $outLink)" \
        > $updateScript
    chmod +x $updateScript &>> $log
    $updateScript &>> $log

    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/shoko/deps.json | awk '{print $1}')

    rm $outLink $updateScript
'''

["shokofin.nugetDepsHash"]
source = "cmd"
cmd = '''
    outLink="$(mktemp ./XXXXXX_out_link -u)"
    updateScript="$(mktemp ./XXXXXX_update_script.sh -u)"
    log="./update.log"

    echo "{}" > pkgs/shokofin/deps.json

    nix build .#shokofin.fetch-deps --out-link $outLink &>> $log
    sed 's|/nix/store/[^/]*-source/pkgs/shokofin/deps\.json|pkgs/shokofin/deps.json|g' \
        "$(readlink -f $outLink)" \
        > $updateScript
    chmod +x $updateScript &>> $log
    $updateScript &>> $log

    nix hash convert --hash-algo sha256 --to sri $(sha256sum pkgs/shokofin/deps.json | awk '{print $1}')

    rm $outLink $updateScript
'''

["shoko-webui.pnpmHash"]
source = "cmd"
cmd = '''
    (nix build .#shoko-webui --no-link |& grep -oP "got\:.*\Ksha256.*") \
        || jq -r '.data."shoko-webui.pnpmHash".version' pkgs/_versions/new_versions.json
'''
