nixos:
    users:
        admin: ENC[AES256_GCM,data:dObGMxw2Dmz+feK6fI2rqTZW/UNjZrcaeBIGOo4AVk4crVwp5PIB+DbQaNjDMr1L8+DHIWkOdD+3vVYcIfSm+h2rehWLXGxPGQ==,iv:RCj5MjwXmJe+hbTa4jNEjQqMYxMfLBc2wxK2n7axx4Q=,tag:GI133pD3j2K6C5gY0xZA0w==,type:str]
sops:
    age:
        - recipient: age1a82mdpvl5w2j0ahyccngc2wvwgrhezrnwn5te99yxy254f9nm54qex3r0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkxtYzhZcXlZcWJnOVhv
            blZ2VFZSSm5pRHJyd0pydGZVV1lXU2VIa0U0Ck9GV0gwSi91R2VvcVNOb1R0blJR
            ZWh5L0lVTTk2WW1SRlNHY3ZOcDR4VDgKLS0tIDFucDJCUVNUZGhyd2d5UmRuSkJq
            RmxzeUVJSEZGQ25jMEY1NVJiQXNRYVEKxkdJ/aceQHLb/gTQeHDPFbnvUqcxSLu6
            fbkm0Z0HArtF9sTLSwGAYsF2V2OOQYOoz7mJ1qaSq2q76kOF6o1yMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVJGcDRQQXJJYTI1cU05
            aHcwZ0JkMk5iR2dYZ08zY0R2WGNjcXZrSDFFClhOK0s4b1puV2FxK3JnZWgwZ2dI
            ZU1nNlBabld0MEdreEVEVTl4KzlZbzQKLS0tIFNuN3NId2xwSzZsN0J3Y1VJd2k1
            K0c4UlZoTWtRTzVUK2VIVmpKZm1rbTgK3Dlnoiri6lalzi2n9hL46szzebiMpkbv
            yII1wWTjJQtH5+6uMp/9hr/cOzf9R4U85DSgyDp5na02g4j33/W+CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T00:56:21Z"
    mac: ENC[AES256_GCM,data:znHCo9gSlKrJ2hEJbseWUuKj7RN7dJDUUbnL0BDu1BKYz8FVfTyk+J6k2aLVQF0Eu9feEtP9DwqTwDx+yZti9yCdBFc8TQCyVe9n/5i6t6X1bAnWltF2QIGacoXVEGIqKbEQGipCydbx7c9RqwvXBfSfkvJ2Ljv9Sb0Oeq3kAMg=,iv:CN9pXkoi7qXKvEXUCLi0CLzIxw6PA+qwi7gOOejFJsw=,tag:0ZlwzT1kEaSDPhjItHVL+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
