nixos:
    users:
        admin: ENC[AES256_GCM,data:dObGMxw2Dmz+feK6fI2rqTZW/UNjZrcaeBIGOo4AVk4crVwp5PIB+DbQaNjDMr1L8+DHIWkOdD+3vVYcIfSm+h2rehWLXGxPGQ==,iv:RCj5MjwXmJe+hbTa4jNEjQqMYxMfLBc2wxK2n7axx4Q=,tag:GI133pD3j2K6C5gY0xZA0w==,type:str]
deploymentThelessone:
    private: ENC[AES256_GCM,data:fDzdO11Kdo8ic/8KbW9QtgexjDOfFanHnu/ZtRuSPfizvfUPzDlDJbgIAF6ekErXFk18g31bR39lP9rkpxd9UZqZSs+QeziKgkhE5ms/WrAeelRXtbHXTq2Ai9VKjx1+kZ8+8s+L6/+5oQJJGuGg8V3pPwlEGKxg9hQCQoFZs8IExx+sS1/mpqBsd4EmQBbcPib9pLgunIXxKtWpq4JMxKy742mjitkys2j8HwoNU9Emqiga9GYTvNvwsinpjKuTQiL4BbuKTnPIrE0vPcX67DaHVPPzIbJabDFeBnkpPnyrkIJqgoHKN/MIcw36gZtTLV1BqrBphHiAgM8pTp08kvFaH4XDss6ORy1pEoGCdVTEwyGsMEHT1CO4JjYJ5mWmKdNNE0yE0yTKqmA+34ERPawbqrWehg4P0EbN+q/KRdOMm5oyBwNaktyt2F9ztHGNYaluazUmm31JNLH5uLsf4fPJJ4hll8f5jS541zK3ngz09aptLUM/wAG5oynFoLQK0pdcTYa0yYf6vMFk+IdURInxym9quf9qaEfX,iv:0AZcG5LrMfP9ssMs9ytm1izlTdVrM8xeiNJG1FU9eg4=,tag:ZO7Su3IYm3Syz1Ff1NB/eg==,type:str]
sops:
    age:
        - recipient: age1a82mdpvl5w2j0ahyccngc2wvwgrhezrnwn5te99yxy254f9nm54qex3r0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkxtYzhZcXlZcWJnOVhv
            blZ2VFZSSm5pRHJyd0pydGZVV1lXU2VIa0U0Ck9GV0gwSi91R2VvcVNOb1R0blJR
            ZWh5L0lVTTk2WW1SRlNHY3ZOcDR4VDgKLS0tIDFucDJCUVNUZGhyd2d5UmRuSkJq
            RmxzeUVJSEZGQ25jMEY1NVJiQXNRYVEKxkdJ/aceQHLb/gTQeHDPFbnvUqcxSLu6
            fbkm0Z0HArtF9sTLSwGAYsF2V2OOQYOoz7mJ1qaSq2q76kOF6o1yMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVJGcDRQQXJJYTI1cU05
            aHcwZ0JkMk5iR2dYZ08zY0R2WGNjcXZrSDFFClhOK0s4b1puV2FxK3JnZWgwZ2dI
            ZU1nNlBabld0MEdreEVEVTl4KzlZbzQKLS0tIFNuN3NId2xwSzZsN0J3Y1VJd2k1
            K0c4UlZoTWtRTzVUK2VIVmpKZm1rbTgK3Dlnoiri6lalzi2n9hL46szzebiMpkbv
            yII1wWTjJQtH5+6uMp/9hr/cOzf9R4U85DSgyDp5na02g4j33/W+CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T07:42:10Z"
    mac: ENC[AES256_GCM,data:WVExyW6vX+sjYwmQKXqG06i0AyKn954wDH+adLT4v+37/SSJ5zsOPu/JM7nBPGZOzXvLVxXKL3FMsotx188WArZwbcwtlfbL3HJSkiqgf00ZF/66hBfV37ErZiiqCy3w7ZwjMMWvuJTtJBRip1I4HUlmgUTjMGCCX9qQ1FXlm3I=,iv:ONpC6wM/QQu8Fs/CnyrecnkNA6LhMNOr/G4PI5OrwT0=,tag:J/MJSyX/e9a8aj7LU9xEUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
