on:
  pull_request:
  push:
    paths:
      - 'flake.lock'
      - '**/*.nix'
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    runs-on: nix
    steps:
      - name: Install dependencies
        run: nix profile install nixpkgs#nodejs

      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Flake checks
        run: nix flake check
