on:
  push:
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - 'configs/common/sops/secrets.yaml'
      - '.sops.yaml'

env:
  TARGET_HOST: theless.one

jobs:
  static-checks:
    runs-on: native
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Static checks
        run: nix --extra-experimental-features "nix-command flakes" run github:oppiliappan/statix -- check

  flake-check:
    needs: static-checks
    runs-on: native
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Flake check
        run: nix --extra-experimental-features "nix-command flakes" flake check

  deployment:
    needs: flake-check
    runs-on: native
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Run deployment
        run: |
          echo "${{ secrets.DEPLOYMENT_KEY }}" > deployment
          chmod 600 deployment

          nix --extra-experimental-features "nix-command flakes" run github:serokell/deploy-rs -- \
            --ssh-opts "-o StrictHostKeyChecking=no -i deployment" --skip-checks
