on:
  push:
    paths:
      - '**/*.nix'
  workflow_dispatch:
    inputs:
      onlyDeploy:
        default: false
        description: 'Whether to skip static checks.'
        type: boolean

env:
  TARGET_HOST: theless.one

jobs:
  static-checks:
    if: ${{ inputs.onlyDeploy }} == false
    runs-on: native
    steps:
      - name: Checkout Repo
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Static Checks
        run: nix --extra-experimental-features "nix-command flakes" run github:oppiliappan/statix -- check

  deployment:
    needs: static-checks
    runs-on: native
    steps:
      - name: Checkout Repo
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Run deployment
        run: |
          echo "${{ secrets.DEPLOYMENT_KEY }}" > deployment
          chmod 600 deployment

          nix --extra-experimental-features "nix-command flakes" run github:serokell/deploy-rs -- \
            --ssh-opts "-o StrictHostKeyChecking=no -i deployment"
