{
  imports = [
    ./nix.nix
    ./boot.nix
    ./home.nix
    ./user.nix
    ./networking.nix
    ./locale.nix
    ./sops.nix
    ./input.nix
    ./fonts.nix
    ./shell.nix
    ./ssh.nix
    ./terminal.nix
    ./audio.nix
    ./plasma.nix
    ./files.nix
    ./programming.nix
    ./firefox.nix
    ./mpv.nix
    ./spotify.nix
    ./vscode.nix
    ./neovim.nix
    ./user-programs.nix
    ./theme.nix
    ./syncthing.nix
    ./wakatime.nix
  ];
}
