placeholder: ENC[AES256_GCM,data:4O9VDWQnvFwcSTo=,iv:2BwV1a2jawsjkrAWKOoMFBjtYeBdsqcjy0DJysW4zdY=,tag:Lnz4V/OKrQWDaaOYAEYlnQ==,type:str]
sops:
    age:
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NUNGZ3FDRHBLaE94TGUv
            ZC8wUmF1QmJPaWowZ25YelRBbnhINk05eDJjCmtab2xOdUtSeXVYcWl3dWlGV29U
            Zk1SUEQwWHN5THVGY0FHRXBQM0ZBcVkKLS0tIFY0Njg2VW5pZGc4aHJGYisrak1o
            ckc0b0E3Tlk4OVhFczNDSmFmdy9sU0UKlB6moqQcIBj2zQ9lCfGUNOSyQ2TbKEgk
            Dg2j/pyWs2G0lwumFVelAFz/QXFSUQkBW55eZNon08euK+m/Z6dE0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T14:43:56Z"
    mac: ENC[AES256_GCM,data:PeYK73WTHhA92XnruFwxLCZFoYyu2nHTWG6XhJoAlexANEsb9EOy4QimzdTipfsY5tzrBfSJKF/Be91Ym2eYnX+Yss545bvZeRpB2RLiXr0r5TKNFf/67BrUMjFDCj98l3S0cE7KYqiVt8pdhNIs8jI+g6V6Kdy/yh6x08a4fTo=,iv:UnDN69PEZ9YIKBVdmRoiBR2IoQa7kcGfLOslO7uVlz8=,tag:go0R5NmKq/am+J+S/wTqMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
