users:
    nas: ENC[AES256_GCM,data:TKq5OSg4HQe6BOSVolWleVKooIe2bII9PGlXAhZsP3PmEn3tXyG1khwJv5R0UKI6cXkvPVenzU2WRFNwoHHtRdlGxijsYJgJe3eeUks22DaX8LPuyws/B05KFrnCA+LXZr2u9qAbMBJrNQ==,iv:7DZYOWkLuQlpVs/ct69m31WqICLKs3OiFocxJvJ+Gno=,tag:liWxpv9QXFgFrIPV8hZlBQ==,type:str]
    hana: ENC[AES256_GCM,data:jm84uRVN1tvQjZB+eHk+dGQR0IC6yWuOHpulpNvlZW4kSucX8Wdws0xAwJ2RUBfZCnR7uQbPlGTTKUDwN9qYkXmq3OW6XW14E387WJOIzK52XPlpSp7u1fTn4p3uOYIA7NCgx15eFwo60g==,iv:OSxfLNEPja2ET6X8cyvAafsDOFghA8ujSDU8InIVSmg=,tag:3lV9xlifhscGpnvvqh/ojw==,type:str]
    root: ENC[AES256_GCM,data:qzfGLZdtATWyyO7q57VlrdRyviFAB5Uk1fgvFd8qi83sDagnCBreEdfBF50mVQKPf8X4Ov/SPAMiTCLV/ptHh+X/VXb9dmBCWw==,iv:qJP21Ooyoe1+9+PV4EoSp0A2fuQ6cD1Hw89XG2l3UtY=,tag:eJwiNvPwop2T4KZfsF6fiQ==,type:str]
caddy-env:
    guildId: ENC[AES256_GCM,data:vqElVtYsYGOymGX+Zo+dBDqF,iv:mXxiqrwWxrBgucocQxSOzcAxSDJWiX9+FeDbjZFrtiI=,tag:jbv7lkvv3WueBa/pALRwoQ==,type:str]
    botToken: ENC[AES256_GCM,data:IIJNOQofRBrgVYFifGl/p3uTLCe2Ocd3y3oaozGiezz/8NkgNiJ0K7dMKh+tMDgyeWHPjiTSDZPTEl7Itc+CoY8HqxvH308c,iv:VEu71EjJuXWM2NsbFSXL6kaDu8CD5B6b72qZhPnbRlk=,tag:0iX3AIwUncSpsSdobyiS/g==,type:str]
tailscale: ENC[AES256_GCM,data:rwqxcvYh7TyWh57XIeTkQLsM1RufpmEj1OD2nZ6xzyF6bJIoL6O909f0gnHlQk3vhqR1DdJ+pNmq+AO/YQ==,iv:PiAAmhXQu9uHScQNalugNQ4qDZJHOx3rOB8WmmMRq0c=,tag:ZMCnCN1BJA3LjNTw9wTYsw==,type:str]
paperless-admin: ENC[AES256_GCM,data:c3M9jGOc8Hg/4hpm+yo5QSYJ8z5JCCl/UQXlcSIdI/0=,iv:WaoSI7SmtM/F+3sN7xRqixfqFTzoOLKcE8a+swJ1byI=,tag:NlXeVZABTXiOQsZaTQl1Cw==,type:str]
#ENC[AES256_GCM,data:KwOBoW1pTKvQs/U=,iv:JHron2ElLEyCfNEpe9bo8F48xYB4t87WksvUg/ykofY=,tag:awGpsliUQZI+kkthtInPgA==,type:comment]
wireguard-private: ENC[AES256_GCM,data:AEYl9JfH/PaEZpwVJ8rhufNStrfOdjdt2JQQ/ASbgTdmbgKt2d5CoEv+yEo=,iv:23GqMshnnMjnGXemTHphLX+1l70hZT7TN+M6ehKgNM0=,tag:LfpcDQNZYsnhJ859ob8zSg==,type:str]
wireguard-address: ENC[AES256_GCM,data:2Flf+aSLjD56DHJ7CjJ63s7qD8ssd8Y46vYZayNdOBDlIGfgbn8O+fNItdkxrEEW,iv:k59kkhpLWo49lBiT4u8H07VrD+Yxkyix6AFDe0ThkTk=,tag:nY6Z5NT6nC+EdB6zOyX2Cg==,type:str]
wireguard-public: ENC[AES256_GCM,data:Yjh/L82Mbo4F0C5ehtlYzMW0z1dy4FxParQVyubEpfibpwLVtkgbO/Jymhw=,iv:KevG58PrLBg2WrpxybLIvDidipqrANttXDRK3E1BOXw=,tag:bMeaq1Q5q51GBdbjWtGFVg==,type:str]
wireguard-endpoint: ENC[AES256_GCM,data:GCRiYhbctNPQJbMy2oSERRZOxCQ=,iv:Qk+5AfENWwSe9NBuywDBT3YdUynzVatoSDsjx0fmbNw=,tag:R4EJDJ+6kpNyU0XXwu/PTw==,type:str]
restic-server: ENC[AES256_GCM,data:NucaxETLpMhgQk3EMx90n69JpgLn4Qc+E5u442gWQaJRNJsg8EOOkJTNiqhlonMuZRzwLppSyoJjykdmbDzm3XwKDg==,iv:WKETixldw3B0wB0kp8ZXOwGg6cmYeExIxL4RZWZJzAg=,tag:eZ+xM17N1RIJ7sWPIx6log==,type:str]
home-assistant:
    latitudeHome: ENC[AES256_GCM,data:i67xo7HBZqQDTsqbR4CDjqA=,iv:lQ9TOwOANgv7cPyL1j5OuqYj0NsAivd+oPbI9ju6kl0=,tag:eHAMunCIMyXzvuRw8+kCvQ==,type:str]
    longitudeHome: ENC[AES256_GCM,data:qekfi/tVHsvd8WcnbrQZT5Q=,iv:SA86U2GD514taqRTeIddZXWBSFvIepMuDe88m45CXU4=,tag:jPQ8s589gomfOnaZTLeWUA==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:VBI6mLDflow/GGH4TbJ/zU9DKmIR6nRegs6fH7Jxguzc1gqMB0QdOKxq9T55n4Qx8SvSdvt5SY8xslf+0TTDToBQl7k=,iv:VRayF71PjhcmgKllivy2O4UYsRXYFD2QbUj1Do61QwU=,tag:2KSgSLA0404BTMCEWPDAMg==,type:str]
    secret-api-key: ENC[AES256_GCM,data:lSWlZyPNvIIRSwIcBh2zCdydZ0xtx3LaQPn3vPyNvaVPjnS5tuXh5orNEsYUGLUX2np4G7ByEhVW8rwvo7yf+B5slF8=,iv:vvE6x/uX5b/Ng85rpvjM3efaZKPEWp++PGPhW8v4LgM=,tag:lhME0uakY53AlfWdfXxn8A==,type:str]
sops:
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T01:49:57Z"
    mac: ENC[AES256_GCM,data:DiFfWml7vXfGkU7oy/8AUzq9LQgjRwC7QjrwbE8VMTxgQ0tLAON2M49FT0xEcs1WrZ+qNmmh48O9hFmYfTQ7bKduYWl0uipcaTbauB+GY06ti+HrlOqnwiemNsFE96n/5WyYpN9JvwFhi0nXMIc7f6+H+htgk/z6DaqM/VycbKk=,iv:xsHi/MGHdfVIsCuWrw/TNizc7UYzfcVa1CYt/MshQxg=,tag:X2XxctqQWSSik7p+jdmKTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
