placeholder: ENC[AES256_GCM,data:89yuCG7ZSFud7Kw=,iv:ab9/rUILWsYp9M/z54G5Xm9cVibiBzU9O6pDi6hux4o=,tag:/INxrQVykh4yuAIDc6oD1Q==,type:str]
sops:
    age:
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeWxQOEc3aUJVanRVd2Zx
            ZGZNamNMRkFyOTZ3RTFlL2dQZHp0dmhseG5nCnY2RVVidlY0TE1VQjFob3ptQ2du
            bHhxdENSempMelRPckR3YzBENjBpZWcKLS0tIEI2TnJ4bFRxbFpIZVBYZXFMbEVZ
            RGdyditYNm5MSVRSZ0hKcWN5bnVmaG8KHOLBOmSZWFuehmtO37n7U7Y23++L60mf
            s7xhrxjKUm5ANWwkBdY2qhq29kzxGqN0kdSda+XtLUqyT+klEDjS0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T14:45:10Z"
    mac: ENC[AES256_GCM,data:Mx8XravNqAWPfZ6EEckDs4rPAZDPs1B75jAKjP6BHL5MlP8AHxQESHZH3JaT15ouF14wa9L72cXn7sOzLD4HYfJc7IR6eLTiwyJp0AsCf9PYTK5l/w+NtutUMqEr/6gGWrD9fQnKfV14Ra446H8z/3mWl4svq6/XR25DXXlnuDI=,iv:gUzhc3gPMzyrsu+SgLRxY5HQfFv9XQ/fl6zmW0ujCGo=,tag:r9HY2XZizxI9P7P7QsMS7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
