placeholder: ENC[AES256_GCM,data:08ur6idIqoLw4Ug=,iv:ciJ8yTlXY5AiXJRt2a/sN846ZyuHyga2Wc6fcoWZKgA=,tag:WkUgacNkdIsIftGhQ1T8Zw==,type:str]
sops:
    age:
        - recipient: age1geuk0u6v70d0v9zvzap8dje9dftftx9q57a4rvf0hhwaxueju5aq80ysvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWjAvaXNvV1VoeTQrdnp1
            UUh2ODFNcUJ6Wi9KcnB5NDZJcU4rLzdwNUd3CjJqeC9oakFtMnNjbndZaWdiZC9w
            ZHNUcno1ZnF0OEtXVzNTMVhlcXh3ZFUKLS0tIEtPSFk0Wnc5ZHhmaHVqRUtGRWNk
            b1c0QlhqSG45MWFmeWtmcDh4NDVJNHMKM2/tkklZ9VKoep/4+EEKvq/lvgMChBUb
            yrNl6hpedCv++eaeXISF685NAoLxKyVIiVWuyurkpvZF7mu+mGh8sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS2kvL1JTOUpxSmV3QWtS
            NUJQc1ZoSXJkc0FBdi9DRW1uUUk4SlA2M2pBCmNKajkzMTBySUw3dkVRNDJmSytu
            Yk5MQnNFWUNHSWVrbDU5cnFkbjdoSTAKLS0tIGVNSXlMZ3JvdVNkZGE4SXNSZzZt
            MDVSNFByQk4rOC9Wc1lNaUc0RlEyNUkKXw2oqNTlfEOKZ1f4BCMUbAMRRFifKfW6
            arvvxoFporHAREx6WWH6kvr9xvfkdTqIPnTFi8DRNHbUxkTUAWYhRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T22:58:22Z"
    mac: ENC[AES256_GCM,data:Y4t2w9tr366j0tC7tRWwO40+KYkU8ioy6gQEuo4atASAza6dpYM3TihQO9yChv2gOVenQJwnF5uTapwGwL56Gsk1NxbtqAD/gj/K0LgbEb4q1c3Jf/ZUr3UBmsWGUIQWO34CedfASCJqNW24XLGZ0DnxYWvDuhFQash2MdCFbvY=,iv:rj94+dQAUyrkiDvegdaOpnz+OdoPryRPzKhGMMcGb6Q=,tag:l0FUZcEtd6SsC9TEgZ4CYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
