nixos:
    users:
        hana: ENC[AES256_GCM,data:cZuJu4kXnoTmYZ/nspRRSKfnCglUXdfOcvXFkfyK5vk+A5urWoqsXOCjPe7vRiOGjRXlbg9i7+JunRFZgf35rjhaff78QOIpQg==,iv:ixS8ufC63grxZM34pKP+tj+cx0ZCtczGAZlbmzm43UQ=,tag:5+s9crmDAwRDTYK2dKKPjA==,type:str]
        thelessone: ENC[AES256_GCM,data:xiClq9nLsCs4M6dpBV6FIgJCDXzOujLCYb3q//4SbHuaRVWFfCqVhndKXvLKHguuVUbCgh7s/swttgdWHV1xWjaNY991swjD+Q==,iv:OFOq4fSiMYzD5uEjPnGj4QLWP01j2nS1U9qK/gNP9BY=,tag:aHPC4pmMppKOFR1fLBaXog==,type:str]
caddy:
    users:
        hana: ENC[AES256_GCM,data:GxRzJHqjwbf3EZ6BVcoHbUTgOhbY/QNldN7t56UZzhP3n/XGzQ+n/+QxKXKsSJxGcGj5RUv9mvdGKbuLlRe57Qc=,iv:pf/OhJh+4d1nq9K4fls4tkvefY0ct6K2qvF/CdqVU/8=,tag:uw9dCEl0otLJtuo0+Tj4sg==,type:str]
        nik: ENC[AES256_GCM,data:agfymNBZCdsy2ah0xZYF1Eq0u4Tp4JlNnNZROb51Z1rNf6IpFHlp6optY3Zt3+8wnPBZ++XqolCJrp9YCfHPjQ==,iv:ysuKkZu2szBC2Lwd86z/AULhXqmgpLph3EFFlGn2XLo=,tag:b5T1NqGKEQ8A1pQ/VGo+pg==,type:str]
        shared: ENC[AES256_GCM,data:hbSn1UynDTGGbp26ISKCDBlTxHVBu1UrseCY02w33pRxmxqBNllwMd2D5+nJ5Z4hxoTI+ToYNPq9h5tV4VRexV0=,iv:wyD25i2H1sHJuCIwdPnOFb04swDKqo+QPb2Y2gUPc3k=,tag:nZ5teY+gZ6w1HrNm8vOmRQ==,type:str]
        thelessone: ENC[AES256_GCM,data:RjnaiIATCtNGNRnsUFaoMj/B6ppJYf/TVwZgxJI/BxFtyTsQWplo7Q45p+TuuOa1vz99mEYQBbSiqLq1P+KPSs1881eE3iI=,iv:FQbs3EFpC1E5YfFrQK34nNU/nCpzqYD80N0vOiL2408=,tag:2RsnZbptXCzayIZdvfTXsw==,type:str]
deployment:
    private: ENC[AES256_GCM,data:yIQS+tVuKoNxN617x8741OkAiSYFehx1hVlBMNvm0uO5LcPzpHk5teqtOIOGq04dZ9Uypw7xSvSFrJ7K1C7eiSf2xyd99/HQe7FtKqLlpeFP+7huiCG/9vZodmU8qpi+/xwBsoMnqIFbgkmcSrx5Fc9LhOA6BqEQhGoplzVQTY5CrfxQ/uxqRbzoTsz/fVwK/eYsRwpa6iuvlg4JDol9xAAFYxs4qusdBdqK9wSd9hd+5lXZThT5j+1IK0yRT8NJIliFIu+E1lnGrwSp/eMQZAef5gxC/BnjcHoWlGdzTi4R49nrhf/3rkq5exN+f2UM8d9j33uNthyMyUJdZ5LO/itzFg0+TevK6zEGnfesqvqiwaU1pL6AIMWpBLfSKXQlbSHVV8ZoTr1OiJ8kdf0krNsCEYWpq5yJyEzB78GiFJsy2ARKLfBqKwbsOG8WA9VR9RT/qM+lm+GsjBbRSkP7eddlKRMJV58fP9kuumaKlc6SpUwVnVMAOmHpoPJVhwKaofDfQ6CKTYdJ8QODb8sykJIZLOyn4jrVyt4n,iv:oiALCOzzm7QcU3O5Y7d67sN9QUOb+YvO49I0pTAFa+k=,tag:cq6YDDCCwbwXoreHwm32Mw==,type:str]
    public: ENC[AES256_GCM,data:636idroxdve7d+FXaJbOpo/rWOv/O4X02r8d+I5EpnK2gu5CKmAkM+ggfejFX9deLYO5ybJ0FVZkSFIv9y0xkTeFDAeZ3bXq8DG+5FM3nTcoEeosDEWP3eChM0/G6d0=,iv:aZGaf3ljrsKf2pyInqau4vsfYvQwaAlrlHqmdEUUOrk=,tag:PXlmbjzmkDac9O6Lq7DS4w==,type:str]
forgejo:
    users:
        nanoyaki: ENC[AES256_GCM,data:uSIrEIWYC9CilyJew4kcwA6febinJBH8fJyWr+OYP5nR061HswTrQop9omlRfuD1bj72hlkvGjZ0B7NWpl44Q4UyjoxvZYAgEZwG8qpbbigU8mtyFlaVS7jVmCZ5s61OHxKCuWTKgrD5ed+QLjf3HIUegmV3ihGkKi+bRPm8t/s=,iv:f7NbqTo+UtYDcZnePerZCT64u0ZNBijSGLIYTvJpaUc=,tag:hOrNRrW2QSW/sM4pevj7Rw==,type:str]
    runners:
        default: ENC[AES256_GCM,data:sdVmrldA5O20CiAqhitrBtjUVSjLjKUrSL5nFSLnGjUHiKUFcymTcCDjXSKkPg==,iv:7IDQTCm3/LXSGWx+0JzAoF//XP6hGd4ojy/BcY0msdk=,tag:sApQhiSgj4km+UWmNJEreA==,type:str]
woodpecker:
    forgejo:
        clientId: ENC[AES256_GCM,data:bxVIcxWMGY0LOfqm58VcCfMdqJ8zu++vJEgIjkQqZkl0hy57y/CttN3eDsdQ3By6JqJxj7HvVTljXYdahfY=,iv:cQRKymbbA//p5TgwBnQrfgZRN0oONQ6Q3GQWkttSIgI=,tag:/ZtDaQwLCsRqCTaP9TYN9g==,type:str]
        clientSecret: ENC[AES256_GCM,data:ihv8kkD4te6r/OFFUkiWn6jDrIdKPa72BF69JlzCbVPTVPesH6B+5vBgKJnFaF4RGmnpdC8AjY3PwKsqjB+omMDOgsQ1yDuWx3WPDCDutVcEkDx9nPIlPAY=,iv:ExAa6G6AF6/CA7o2ijJotbH9XdbhGEJ6MYapMo8PXR0=,tag:taplZPYCuvZRAj5G9wHkCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bThxbE53MTBaZ2srZkF2
            R1VVMTVpdTVNMDZYb2hwYXFXVW56cGY1V0hNClgxM3ZDcHBHZzFBaWw4OU8xVHhM
            WUdlK0Y5OExURit3cFlPNUJXalp2Z00KLS0tIHNWanJrVFZrUnF3SHpKTFpxVW5p
            L2w1S3lMUENRMWJ3QzhBRGFTaWg4cW8KN8ya2LNuM4p0YmJKZILuBglpwRzh1iTM
            kLo+JwetbGIByK1br3je3yFfxo2dcBVEJ8uMpzAS2S2PTJWcft8uDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T16:11:58Z"
    mac: ENC[AES256_GCM,data:NX5LBXECiSCwfIiTJ88IiWbp7PIuA1DBXgDtuOyMp5Ib2a0ZmdqNLHXqFibutQYuyGLiZwQ4/6BeEjztydTuhao7E6ieRylZTm648uakCeenmEh3/dk5h3T3hoyQftbm+wGtOODzr78aqdaB15u6m+EY6Xeq6H/tBL1aT/heyME=,iv:DfXyo/9glygdQWwnWMtRC1XpcwnbD9LnLi83/XdWVA4=,tag:SYtP3rHnp7iXSbiytIPdQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
