placeholder: ENC[AES256_GCM,data:tEsvCWDWGwInHu0=,iv:aNT0pOA0oRHxL7u6uuUSEeKe572LrNAjo082WS5lvZk=,tag:1s/3jMzh3+v9TTRnzDtl7g==,type:str]
sops:
    age:
        - recipient: age1l3s5ckneu4reytw4ecyt2qcc49hf8kpx0s89senr5yhf6fqu3y0sxkv398
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUllFWU9Pek1RY0tsNUNr
            ditpZkZwcDJWdDNMS292T25lcTNYdDNGdlZJCjdHQ0p5Tm5wUGtTRUJ4VGJCcGNn
            TGx4QW9pNER5bzF0d2Zva2NLbVp0WmsKLS0tIFJCbWlBL0Q2SWEvN0VYV2x1T2x4
            V2tNS0ZaK0RVUW1kMUxkbDBCQWU5QzgK2AGUT1SA7Ap6C+e96p7POdH2Bie0uI8U
            vXOrfrQx5fSCAxtDdE4Y4dL5bWYvpX58bR7DmFav3i+TWYG4yegoIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSEFEUDJra2NTTml2Q1U2
            RC92a21mQ3hrY3ZURzJubk1DdS83d2J3MkNnCjREMEZCOHdLWnVQZVR3NWthN05x
            anBxamM4dDZEVVd0bkJBOE4zZmtFTmcKLS0tIG9ldVhneVZrbTRQNGhvM2NYcllp
            enpuZk1HSFhCTU1vQ2FSaTl0djdlRmsKb+/aYhHRlmCRgC/5aTZs+erh6mhoHQAt
            Uy9W/F32WM0rvB04pozzjzPN/7797HUnvoF4PDhxTqUotcLjw26NEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T15:49:43Z"
    mac: ENC[AES256_GCM,data:JMNfiy/3VK41KoByjNumjgaxS7EL5WRbaNvr+zDjSGJFDQR8yeIxX7f07N+JQsqA2iBXoAlpKrOaJTFd6QShsnMJN7JDYQQe5lGLqEw+lV6HJgSR963R70DEgQOc4IfC81WZBz+gRbjnfMRSgQQyZLfIesAgdsmp9ptucHIBMs0=,iv:vWHYH1RtVp8KFs5PAGcvDNHdQp8yMNRNOSD1LOpmoVk=,tag:mydhitvqpzvRzPgApKyO3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
