nixos:
    users:
        hana: ENC[AES256_GCM,data:6EPtzM+kgREs4I1vOdpinnqI6IGr3LEc+FtQxD5BulUhOv9yZPVw8OBkd/qc+XKDH49c1ZnbegtcILthKEnH4L0qGK9LrJ/PODTAkx3rT6xS4zox/ZqcLrqk6xPWcCJGbkKsmcT3JBYT4g==,iv:5O9jWjDyPOHbI9c/XyU+mdURSRLYngQMdgDjrMeI7Ho=,tag:QFrmwJSEio1Ep6nabkwiuA==,type:str]
syncthing:
    cert: ENC[AES256_GCM,data:AHBYxraGbGrbm9GBAkzsmdvWF46zs6kRzYi2ltiwqthwgTtMNJGraEEj+MDMej5z3JlDi/X2drMtJfJSTEPcwjCFXNfl/Eh2/7QGKLvLvVE+XgFBuvNdQaMNb2QkmOKA6qWJb3/ZFJdHneYuuss9n+oH+J8HTPjXFyNIsYuNhmvgqjzLkc2sYaK+TiSkCgP0sVEQ3BFIx8jTlDXG81i15rmOkBmtbeDvCnCT+J+JPtmd3h4a2IIFTPBJ7/kroZXU9TyfXo+eZ8lclpvllnskcw8aurX6GMWCJQ0+xL7gQQywWhaYVNMUtpA4g3i8Iw3k+ekrYhQgwkawg5/PTjJk1i0qXQW3FjJaleGf/vGaAOCIaeZ5x8V7xXIk7isX9YarUNqqtgRs0aJrv6EDxw+VICYsa5aYr6dxDepKMlh0g9c0D7rLONmBBD6qxYfSwiN0h5mK1T/l+SiUr4FvXujhEjgyoaWyg+iqQLCKCSEndlN0xNBqpTknsJ42pOG0lytpk7I2whSp6UNUTHd/RfJCHBHCkyb9qyt9VaYaIvwkr/pO2FDQKa3e42nOsCsPlo3uBgCwr9+TLozkAf+gbi3YrigjpTcDsLtqXN6NOOtgaYuPLawZKCp7LnteaZYC01K9VCxSx3Me749SL9EXwaqoppveCVsgXnTxtSph8/4el2wm3v81DImf8yPx4JDMfeRHTL0fF8zX6s/pVPfeLbPTt5gy8eO1xl6xEfbQrVuIybd7Gonz8KEqvCCjrduY9c0yFVMs7U+X5xgcpL+4fTS3+wF+Hwo21B7z6/fr6N0r46yb2LMFGYClYxuPHEe30i+z3btwONQCti2rawW/CKdqnewwVjK8EB/7Yge8kGkaDD3QAmJWMTnM2ohjkQzOZjCzRQiZwupih6qdr0FTQ08dUa1jYvOJqUcTLA8VmHoNS/Ck9EeoI0v/bkmFXqhtOLauss8WHulR5skt3w+FHeI47fztirkhF3AW1TBJb1WsVsNo1+uFdzbyE6PaQ4FU7TnCqv93yaH26UiGFrlbes8furgQDIm6e82Wf+A=,iv:CX+mhhbg8TfKeHHJ5BLwGcp7E6iHnfldpife5QYyRgc=,tag:qDg+NRBOlxhs0+57R7l5Yw==,type:str]
    key: ENC[AES256_GCM,data:toX3f93XnGOieK2Ab2dgwmfAiSNsB/a1hCYfTVg4cyHW27ZvSVymun2l3WgPETkuPapz3B+Xk8FTjhwMmRhz+BW7M40vDwEytYemGHuK9Il2I9kcXRvfcaZpYAyMzXMNwueKcLMvwMPT7HHCo77kNgVcQU9X3l7RNC/ocmmfXr7/nM6TLpfnCtxjs6Lh0YfzfWjjqVxVT6uzrwA5Cyv83V4IoysIGnDhI7MS+cSCBSk2fKSTjovLU3FoJE6n6jNTsiqb+A6yQGvT4+MKGkfMkT4qNAOiAEWRMHtCNftYcgbP3m0vKL+5ICE8irFZdwOOVycJXS6rTPy9qBnHChLHJtpI0toRFpAD/Rh34pBi9B+kqYL3b3lf9+10159SAGNG,iv:v87Sv6hqObj3knv1W7PBNiB7xRhJmI/jNifltAsnm30=,tag:Im6Fn+XiyA4w2v+5KjQJhw==,type:str]
tailscale: ENC[AES256_GCM,data:1AA4N+9P7K9jYOdQgXOXi4QKML9CRvQx3veJdUjx7gaiO3CHGwf5zoA+d83O/CrdY/+AFeBpkrCirD02iJw=,iv:k8os1CyhCQm8Wz6PeQQrR/Cd4zKKnW58gIlPdaHmz5I=,tag:rpFuTQzI6OdXWQsNeC69rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age152k4hxe5vyj6kq48w4dqcm3tadyr7f6u02ydgfu8s2uuu478jawsj5q3yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RlByaWRRay9RTkpWVGMv
            dEM2VTRtc0tCRlZDR0p4cmdxNnd1WE84TG53CmppS0dtSUUrWjlMSjlYNjF2ZWRa
            c3FKNUE4QzZZWTMreENJcjdETWg5dW8KLS0tIDg1emMvN1RUNUlFOEtJVC95bjVo
            azQwZGV3cGEwRGthRytqZzVEdU5UbncKmoA/gVAzaY+5jgRP4U8JTnkVzHS9dCro
            jURDgBFYna95Hcf5ms34xjj8o6wx0oO7v1qj6eBfp4/AO9dTqA/JyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0MwNW9hWEtGYVZQSEtm
            SWsza0pqU2tKcTRFV21nZ0F3d1djemNlQmlVCjBaUHdvQmFqMUF2WG9rL0JmeFpM
            QWpCSFVYSjZ0TFpKOGhhOGVBTlBUcTQKLS0tIFAzNStaSVlMbFJ3bVlOZUFwQVRG
            T1JXbnF3MlBUNGYvb1d2VGxDTkVDZnMKsnzJqVNSoBioZ3g782lJ/XVkBgjR3VVA
            HARAEOnI9x2CRcPnc79lMFYlSfRb3mVD5RFf0vuIeEK2TzvZVZXy8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T03:28:31Z"
    mac: ENC[AES256_GCM,data:HGsWDcr4UMW4EtKJpGywOouB3dxF5+B18jibPv0pbT8LR5vqelohVpGGUASLAUY0M3lrKLG+KdOD4cCUvUTqmSK9ILW1Nuuio7iv3NYwvU7cfY0mWn8/vlbQfOr6Pf1EvzNeyXsMeSndGfaR3BPkYWRhCNhM1GMQrcL9IbTsMms=,iv:l+t5tROjaGZ7SM/ynjyfS4FRTK/sELo/RBTTeGWMcN4=,tag:/glsADC0WMS+VnA0TevL5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
