nixos:
    users:
        nas: ENC[AES256_GCM,data:z+0fZwJddL2Qw/K/LwkqVs8A3Grm/FvAVs7Jtf/0PT1Z+uqedCdHTpm0sEwnNb3tiYkHZEZ1Fo+DXkxEuMKqKuPyxjq/HJ6H99iaoDEM/W9p0zeVPCgGH640qFqwjPw41DfCXVd7+MdaUA==,iv:jCmG7zYvQskyIKX9WFTAgWFXK/HdfNb+PmUAO61MdEc=,tag:9xJRNcqkRHCnUGDbIb5uNA==,type:str]
        hana: ENC[AES256_GCM,data:Z0tbveZcE/3RB9QfV6F78Abz3xU2DbRT47PO9Npeq28Tx8bUb1JZSzIAH8xwfUd6InUHtrl/qEsJfgIb8EJg1kuBZ99K/48BUrKWisOqvnSiaUIEfxQu1x40HimmranBQQmRsp7VlqjoXg==,iv:KMzW+Tygl8gDFnSInw8e97ezLnCqFMmSLFLveXa2U7U=,tag:caWsMz1BhkY+R/gjD1C8WQ==,type:str]
caddy:
    nanoyaki-events:
        environment: ENC[AES256_GCM,data:oB0KyySIPixQkUmm1FgqO2NXD6WGS09jnfhYjsTaaeJFEoZXiLAXW0S58VlRicyyP4N3/59ThZYpulKIDm1awl/0BMj1a/s3YUwXXsPgkbBLBmMz/cNSO3mPgdf+qD2Rs+666Qn8sE8Pb4XNul5Qeajht5qqeV5XM78Wj7ujsKrrMGwnKTERr3bDcb7224RgvDj3dF72oSKFbpu0wYJEYKTW46guFaF6IHMJemC8ghKlTF7WJvIZHliFREM9xrhC5kzrVFSF/6lX3CYKBRP9y6/Ma4nQ+aSks+1oY3g7ZZ2doitJ/t0ry8DklQ1XVe9hjAqIU8sk/6b7rWyDwUaY+YQ=,iv:CGgp0lsqkS+FQHei4M/fUfHV/36Zh++2alCzYjUUwYE=,tag:QebnJKcSl4jDIJco9KICow==,type:str]
dynamicdns:
    nanoyaki.space: ENC[AES256_GCM,data:mh9ZKgo/Bz4/58ZIRztT2Fc8OHQwPkPYQXkdz9wl1r8=,iv:SXr69Uq33xXP1y73jdZgvDRZRezP0q4vm3CgkF9n4FY=,tag:fT3Y/ZcOM2rNKj6dSYLr8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T14:30:25Z"
    mac: ENC[AES256_GCM,data:F3mRZUOrEtiFGRB/itjqkoRbW0XmcACJolXDK3Xj32M8wMXSyhykTOJ4bbPkFb7l6bPk7KCZTog/kSQNSZbXiF5QWDSYHbOxwnbQzDf1G0Cylub9hkwnpZwXDgDGH/BGLdwaYAHzXNBEMHBG7Sluvgo3hs7vqHFzUrWQcdr9fRc=,iv:l66DBheOh7tic4gzd496gqZZM/ugnk1Il/1BZVwrElE=,tag:69EG2xTGt6l3jWl+IH6cjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
