nixos:
    users:
        nas: ENC[AES256_GCM,data:z+0fZwJddL2Qw/K/LwkqVs8A3Grm/FvAVs7Jtf/0PT1Z+uqedCdHTpm0sEwnNb3tiYkHZEZ1Fo+DXkxEuMKqKuPyxjq/HJ6H99iaoDEM/W9p0zeVPCgGH640qFqwjPw41DfCXVd7+MdaUA==,iv:jCmG7zYvQskyIKX9WFTAgWFXK/HdfNb+PmUAO61MdEc=,tag:9xJRNcqkRHCnUGDbIb5uNA==,type:str]
        hana: ENC[AES256_GCM,data:Z0tbveZcE/3RB9QfV6F78Abz3xU2DbRT47PO9Npeq28Tx8bUb1JZSzIAH8xwfUd6InUHtrl/qEsJfgIb8EJg1kuBZ99K/48BUrKWisOqvnSiaUIEfxQu1x40HimmranBQQmRsp7VlqjoXg==,iv:KMzW+Tygl8gDFnSInw8e97ezLnCqFMmSLFLveXa2U7U=,tag:caWsMz1BhkY+R/gjD1C8WQ==,type:str]
caddy:
    nanoyaki-events:
        environment: ENC[AES256_GCM,data:Spyk5vw/L0KfnrafzSQ7NBTtqiSd5m9OdNyzQUIelUAhQH4BX6e522BMH+7Eqg0kwQku7+jS0E6EtFcHLjaeY/69veKXxVE+zFNt6Kc9lonJ/DAGB/hb0z/8j0JvlSXVa+udOBuo82xeFZWaSVgrVfv28SCUpluGpyX+/HaGe4ZK5zaciFeuIoikLnxQlOv1JxusVlnVemEiLoCbeQpZKv/UraQh6ej0E2sTH/1HfIWk9aKO8DlZ9yDFsYjtV9/lK3nkkb0NuJ8FLPJcZHT8eJf25KbSmGK9NQZn1ZdgtgjgXtqQ1SoKhJVtrfHF9TzR5cvUTZTcKQ==,iv:sTI1EV+brpFEPYnPLEbLkh1FvadvgZR0cFbM4wvbBfg=,tag:/2+ltUe3UkDOd+4dJt8dKA==,type:str]
mongodb:
    initialScript: ENC[AES256_GCM,data:NvWhwYz7IK5279ALkgvd3bkQIifz08zeiaJnCerK0IQRrzXfFtk5z3DQXOM3d0fuW9t4up/C+cCp8sLyzFqxgh+6/ohqkorK2UCAHzZHGPqbvf22hBN2+bs+e889wwTu9WXPh5LOwYzr+aPD1fdpx35EpnJZyL1GuKjVBXjD/1Mjxp2gixVeatr3N64mZew4cgvRJaH1uJr8zkYSasPcEk/XevRfKSmXc9x5VVOCP+lrEpeewPuA3oVuSxJPTwLGmLDRCje2YLCZn1Kl1p9vsLOb0rrg04BMZhQ=,iv:TDu5esHzIs22hegKjiXj5eyONq85G4YYAEa30S/hJq4=,tag:TZc4vlsPHzYhm3VS35Negg==,type:str]
dynamicdns:
    nanoyaki.space: ENC[AES256_GCM,data:mh9ZKgo/Bz4/58ZIRztT2Fc8OHQwPkPYQXkdz9wl1r8=,iv:SXr69Uq33xXP1y73jdZgvDRZRezP0q4vm3CgkF9n4FY=,tag:fT3Y/ZcOM2rNKj6dSYLr8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T17:42:28Z"
    mac: ENC[AES256_GCM,data:qVfFLYzGcj9SF0Bjnff11NFfFlr1Dxo+lrGgOTm+f1kU49VFzo4jP7KGqo+N7uUQelSfEDKf0HErYqxPTWL9u5by5IhfL9xnAg+Bh8FGTwLDKKdPHM4L4mThApTeKu+RcTtXbNd/tBbqQS9gRxSL6SVWXQHgvvSQxN7H5SfXoiM=,iv:ibdq9U5asj/jPWJTh0ED18EEd8gznfSSMo/qsRWiZy4=,tag:IuwGOrpn+BE9heQZcJq7vA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
