nixos:
    users:
        nas: ENC[AES256_GCM,data:z+0fZwJddL2Qw/K/LwkqVs8A3Grm/FvAVs7Jtf/0PT1Z+uqedCdHTpm0sEwnNb3tiYkHZEZ1Fo+DXkxEuMKqKuPyxjq/HJ6H99iaoDEM/W9p0zeVPCgGH640qFqwjPw41DfCXVd7+MdaUA==,iv:jCmG7zYvQskyIKX9WFTAgWFXK/HdfNb+PmUAO61MdEc=,tag:9xJRNcqkRHCnUGDbIb5uNA==,type:str]
        hana: ENC[AES256_GCM,data:Z0tbveZcE/3RB9QfV6F78Abz3xU2DbRT47PO9Npeq28Tx8bUb1JZSzIAH8xwfUd6InUHtrl/qEsJfgIb8EJg1kuBZ99K/48BUrKWisOqvnSiaUIEfxQu1x40HimmranBQQmRsp7VlqjoXg==,iv:KMzW+Tygl8gDFnSInw8e97ezLnCqFMmSLFLveXa2U7U=,tag:caWsMz1BhkY+R/gjD1C8WQ==,type:str]
caddy:
    nanoyaki-events:
        environment: ENC[AES256_GCM,data:sj0IerrdPeJmcWpaod3prU+KAKQkkJyNYeMwKkrnxbs1k4qjqJnkfWr23euvlPoEsGd+/mMuiuhczCm1Hq7vTTcvjkiNmI03EWoPfV6RalecfxuKV2sIrpz/KscjxEy0ZkMejCRzCSFmO8ZseZE5+ogLs3wnFZb2i2SxMi3EiLvKO7+TDv7WSowhPVOEoNfv26yOUaRLkdH6/I8fNl5MNCuU/3lkSU4fJD1MiTZCz0FOlW9ECmCKVABdJw3GaHHfCuUBk6cxIq59/6ltEbA7/9x09WDO,iv:5v2/5ZUh8n/3bE1PyKCd7LZeG48foNEl1H/EeQuBZzM=,tag:xEk880/vTeFvtS0lwaxMMQ==,type:str]
mongodb:
    initialScript: ENC[AES256_GCM,data:3z/LxfNJfIPTsTKlJdjaEWOug72pghiMHRTw27jpS3LYq5BveASAFLDBy0XmnMcjrsoDdEYJ08Qi3iXEQ/7DyKlg9JKwmqgowWSykGazhXQ1Mzr1twwMQedfHelE72d1ypzlLgZCookQuHS53KviSxbvwBVRbskHho7oL9yZ/isB0+QWzJdsCjjld1a5X2VVOp63bG5ySWIIpb7vDVjF82v4D2kSWc/4IXB6yURO42Z2QncnTHu9ykO4BquPFBw8k1PcXyC8B8Qsss7158vP+Q==,iv:LKTj5PeGa8y6LHYgzKpx2bwmPKJdZ48lmdFcvMrN/IY=,tag:Tf7h5Y00jjLhzGHiwySPaA==,type:str]
dynamicdns:
    nanoyaki.space: ENC[AES256_GCM,data:mh9ZKgo/Bz4/58ZIRztT2Fc8OHQwPkPYQXkdz9wl1r8=,iv:SXr69Uq33xXP1y73jdZgvDRZRezP0q4vm3CgkF9n4FY=,tag:fT3Y/ZcOM2rNKj6dSYLr8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T15:23:52Z"
    mac: ENC[AES256_GCM,data:m3UV5W/n0ghyLa02MunA2Ef8p2jFWD1HMcnJMWqN0rIjOCvIyAgw9YtFQzQLyx7dMMqr4q8A3MP7kbeqKOW8S/mqQWtylKCkU+oaLwhi3ZXf5anIyNt24/uiD9By3cN3SUvJmXJMXLXBbBUYIFPN6liG32MNYyQ1AzTEyQbGiSU=,iv:hkaAUqtHjtl9GUdtw5QXjKxQSiu9Ae2Qj8ywe/hHLwM=,tag:jSph+XtB0gBJ5PXijC5yrw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
