nixos:
    users:
        nas: ENC[AES256_GCM,data:z+0fZwJddL2Qw/K/LwkqVs8A3Grm/FvAVs7Jtf/0PT1Z+uqedCdHTpm0sEwnNb3tiYkHZEZ1Fo+DXkxEuMKqKuPyxjq/HJ6H99iaoDEM/W9p0zeVPCgGH640qFqwjPw41DfCXVd7+MdaUA==,iv:jCmG7zYvQskyIKX9WFTAgWFXK/HdfNb+PmUAO61MdEc=,tag:9xJRNcqkRHCnUGDbIb5uNA==,type:str]
        hana: ENC[AES256_GCM,data:Z0tbveZcE/3RB9QfV6F78Abz3xU2DbRT47PO9Npeq28Tx8bUb1JZSzIAH8xwfUd6InUHtrl/qEsJfgIb8EJg1kuBZ99K/48BUrKWisOqvnSiaUIEfxQu1x40HimmranBQQmRsp7VlqjoXg==,iv:KMzW+Tygl8gDFnSInw8e97ezLnCqFMmSLFLveXa2U7U=,tag:caWsMz1BhkY+R/gjD1C8WQ==,type:str]
caddy:
    nanoyaki-events:
        environment: ENC[AES256_GCM,data:zEmlGvtMiovEtVBwLYn9uTiTOLh26Bs2WLZbyTb6Ngt5Kx2YsYmKUOPXVRieBd7KrjwnlaXUrg2GUjVfovRPw+d/IrAnv7j91eU56yL7NlUE6pMyFOL7hAAc5jDjHzp1vL/MDmBK+F6oCcBNGW9Bc2hdGw==,iv:gqNAbyfhhO6lHzZ8GBNGpp488FVd3VOTt1zaZlyPLuQ=,tag:C0KlweKGkQA0hZM+hQ/Klw==,type:str]
tailscale: ENC[AES256_GCM,data:rwqxcvYh7TyWh57XIeTkQLsM1RufpmEj1OD2nZ6xzyF6bJIoL6O909f0gnHlQk3vhqR1DdJ+pNmq+AO/YQ==,iv:PiAAmhXQu9uHScQNalugNQ4qDZJHOx3rOB8WmmMRq0c=,tag:ZMCnCN1BJA3LjNTw9wTYsw==,type:str]
paperless:
    admin: ENC[AES256_GCM,data:H1uHx0+8S87T156AgQmO0QNIBfgR1os7A6szAF3Lewo=,iv:nOoVsiuTqmf6Pa9V5IRhmfxULfQxeKXTYAWqbwdQji8=,tag:pJ5yIdFPpjn6nD/s4ifcNA==,type:str]
vopono:
    wireguard.conf: ENC[AES256_GCM,data:OuiOsT3mvoPVe43v9+wrAuw0FGCyWht7La7z4wn3lIOjrC4yh6l2Rfla0WnmK6MQ2V5fmxka7o6N8WYzHH/8mpL9/ZgWLYYatb7RKoyxLiCrgbn6uXlfphY/djuWdZUg5CH/vwJp+ZIhAu8i2I5FtuwqJJ3+0zwY5y78IgBAGQj0stpI43X+wy2bO4o7DTK79y/exGuw+IcO0x8PPvZiSrnbtkpxy/hIWuGLaTS1OUYUh2YMCkDgGhwltPkYMtOnO2BQAhW0pGumewmcjL81uRMSza86EBXJ14UDO24bqyRT4zxlA9C1R/ujq21833j09HCBlBfwVrot9uhSe/wf5nLJLbPC3S//TLdsAhzZt5+EeKbIAyJGo5fvf6CpZkGx8JY=,iv:3OSFTHNe3R/tfS/p4114E0xOskG9LEGjrFyNEXSn73U=,tag:YbJKcnpZQB+0Pvm2KCoukg==,type:str]
restic-server: ENC[AES256_GCM,data:NucaxETLpMhgQk3EMx90n69JpgLn4Qc+E5u442gWQaJRNJsg8EOOkJTNiqhlonMuZRzwLppSyoJjykdmbDzm3XwKDg==,iv:WKETixldw3B0wB0kp8ZXOwGg6cmYeExIxL4RZWZJzAg=,tag:eZ+xM17N1RIJ7sWPIx6log==,type:str]
home-assistant:
    secrets: ENC[AES256_GCM,data:bCl8fbzydfcNd0gPF8gaDoXYmi+AzhmkznqYns4c8n3D17DnHupBKbhZjUaxDZZIrXq1EK0Ee93hmAic5nejsuAkHg==,iv:ROfx0puoPv2j63Gg3GpzC1ED88VlZG4Qtp2F4myOT1Q=,tag:uNLYtfZcM4mqQY+wFJISWg==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:VBI6mLDflow/GGH4TbJ/zU9DKmIR6nRegs6fH7Jxguzc1gqMB0QdOKxq9T55n4Qx8SvSdvt5SY8xslf+0TTDToBQl7k=,iv:VRayF71PjhcmgKllivy2O4UYsRXYFD2QbUj1Do61QwU=,tag:2KSgSLA0404BTMCEWPDAMg==,type:str]
    secret-api-key: ENC[AES256_GCM,data:lSWlZyPNvIIRSwIcBh2zCdydZ0xtx3LaQPn3vPyNvaVPjnS5tuXh5orNEsYUGLUX2np4G7ByEhVW8rwvo7yf+B5slF8=,iv:vvE6x/uX5b/Ng85rpvjM3efaZKPEWp++PGPhW8v4LgM=,tag:lhME0uakY53AlfWdfXxn8A==,type:str]
sops:
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-05T22:52:52Z"
    mac: ENC[AES256_GCM,data:/Fh4DOC7RG/YwLq7sIlUxUXbsTD/9CVukye1f7vFOTqMNdArlbvXsepJYHvhFUeB4QkGsqFmjRCCOiEz/gay0jRbey44dW5hof5hr3VcEe/MisAQ/16p8v5BErbOi3IKGojNoBJwjVvp3RXpPnJOHZGBgJR0KAb8l1Z+abxrTIw=,iv:7XGMtT47PRbWz6JJ8rxb6YUY8vDRVfsux6j3nOIYPsQ=,tag:skjaJd821kCZObfL4xcyOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
