nixos:
    users:
        nas: ENC[AES256_GCM,data:z+0fZwJddL2Qw/K/LwkqVs8A3Grm/FvAVs7Jtf/0PT1Z+uqedCdHTpm0sEwnNb3tiYkHZEZ1Fo+DXkxEuMKqKuPyxjq/HJ6H99iaoDEM/W9p0zeVPCgGH640qFqwjPw41DfCXVd7+MdaUA==,iv:jCmG7zYvQskyIKX9WFTAgWFXK/HdfNb+PmUAO61MdEc=,tag:9xJRNcqkRHCnUGDbIb5uNA==,type:str]
        hana: ENC[AES256_GCM,data:Z0tbveZcE/3RB9QfV6F78Abz3xU2DbRT47PO9Npeq28Tx8bUb1JZSzIAH8xwfUd6InUHtrl/qEsJfgIb8EJg1kuBZ99K/48BUrKWisOqvnSiaUIEfxQu1x40HimmranBQQmRsp7VlqjoXg==,iv:KMzW+Tygl8gDFnSInw8e97ezLnCqFMmSLFLveXa2U7U=,tag:caWsMz1BhkY+R/gjD1C8WQ==,type:str]
caddy:
    nanoyaki-events:
        environment: ENC[AES256_GCM,data:TA0ZOb9IClpwAVypJM7n4CQILj2h6bAE2m6AGvc8K21NRNK5ZdTCmjo7SjJMOGGFLa9FAqttM6JXQi0zqlwyzLUd2qdOLmhaWARtx1+5ACzBQfi83qK+WO9vA1/cOncLw9VMmNYtj1UvGdAA/rPfNQSLeIGd2J9rpW9+,iv:+ocBtk3jXNVxZY31kj500EBidy7H7kuvf4rNVAYDygw=,tag:Gcn0c3zyuj2yt11LMNwzTg==,type:str]
dynamicdns:
    nanoyaki.space: ENC[AES256_GCM,data:mh9ZKgo/Bz4/58ZIRztT2Fc8OHQwPkPYQXkdz9wl1r8=,iv:SXr69Uq33xXP1y73jdZgvDRZRezP0q4vm3CgkF9n4FY=,tag:fT3Y/ZcOM2rNKj6dSYLr8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T18:30:32Z"
    mac: ENC[AES256_GCM,data:skzDvBb4PPp7M48hSB8KszaxpeFNGkWn8sjCtwZbdnoqHKufkm2RhEVsOwLS8hU7N76bJVkXZ4Cb5EABIPrUz4DgsEjNMgHH3F+AWBqgz7YqEJwrHNVmODb2mzXMdi1darDRkoyL25QpHRwcLY3Njgu8hddRTXjdEJP9IcVGcdI=,iv:0nSU4tyLc/wAH9wFVem/VSRJP8XIE++ExzWbRTVtEnM=,tag:im167QXidUFm2RWodE2PzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
