nixos:
    users:
        nas: ENC[AES256_GCM,data:z+0fZwJddL2Qw/K/LwkqVs8A3Grm/FvAVs7Jtf/0PT1Z+uqedCdHTpm0sEwnNb3tiYkHZEZ1Fo+DXkxEuMKqKuPyxjq/HJ6H99iaoDEM/W9p0zeVPCgGH640qFqwjPw41DfCXVd7+MdaUA==,iv:jCmG7zYvQskyIKX9WFTAgWFXK/HdfNb+PmUAO61MdEc=,tag:9xJRNcqkRHCnUGDbIb5uNA==,type:str]
        hana: ENC[AES256_GCM,data:Z0tbveZcE/3RB9QfV6F78Abz3xU2DbRT47PO9Npeq28Tx8bUb1JZSzIAH8xwfUd6InUHtrl/qEsJfgIb8EJg1kuBZ99K/48BUrKWisOqvnSiaUIEfxQu1x40HimmranBQQmRsp7VlqjoXg==,iv:KMzW+Tygl8gDFnSInw8e97ezLnCqFMmSLFLveXa2U7U=,tag:caWsMz1BhkY+R/gjD1C8WQ==,type:str]
caddy:
    nanoyaki-events:
        environment: ENC[AES256_GCM,data:zEmlGvtMiovEtVBwLYn9uTiTOLh26Bs2WLZbyTb6Ngt5Kx2YsYmKUOPXVRieBd7KrjwnlaXUrg2GUjVfovRPw+d/IrAnv7j91eU56yL7NlUE6pMyFOL7hAAc5jDjHzp1vL/MDmBK+F6oCcBNGW9Bc2hdGw==,iv:gqNAbyfhhO6lHzZ8GBNGpp488FVd3VOTt1zaZlyPLuQ=,tag:C0KlweKGkQA0hZM+hQ/Klw==,type:str]
dynamicdns:
    nanoyaki.space: ENC[AES256_GCM,data:mh9ZKgo/Bz4/58ZIRztT2Fc8OHQwPkPYQXkdz9wl1r8=,iv:SXr69Uq33xXP1y73jdZgvDRZRezP0q4vm3CgkF9n4FY=,tag:fT3Y/ZcOM2rNKj6dSYLr8g==,type:str]
tailscale: ENC[AES256_GCM,data:rwqxcvYh7TyWh57XIeTkQLsM1RufpmEj1OD2nZ6xzyF6bJIoL6O909f0gnHlQk3vhqR1DdJ+pNmq+AO/YQ==,iv:PiAAmhXQu9uHScQNalugNQ4qDZJHOx3rOB8WmmMRq0c=,tag:ZMCnCN1BJA3LjNTw9wTYsw==,type:str]
paperless:
    admin: ENC[AES256_GCM,data:H1uHx0+8S87T156AgQmO0QNIBfgR1os7A6szAF3Lewo=,iv:nOoVsiuTqmf6Pa9V5IRhmfxULfQxeKXTYAWqbwdQji8=,tag:pJ5yIdFPpjn6nD/s4ifcNA==,type:str]
vopono:
    wireguard.conf: ENC[AES256_GCM,data:OuiOsT3mvoPVe43v9+wrAuw0FGCyWht7La7z4wn3lIOjrC4yh6l2Rfla0WnmK6MQ2V5fmxka7o6N8WYzHH/8mpL9/ZgWLYYatb7RKoyxLiCrgbn6uXlfphY/djuWdZUg5CH/vwJp+ZIhAu8i2I5FtuwqJJ3+0zwY5y78IgBAGQj0stpI43X+wy2bO4o7DTK79y/exGuw+IcO0x8PPvZiSrnbtkpxy/hIWuGLaTS1OUYUh2YMCkDgGhwltPkYMtOnO2BQAhW0pGumewmcjL81uRMSza86EBXJ14UDO24bqyRT4zxlA9C1R/ujq21833j09HCBlBfwVrot9uhSe/wf5nLJLbPC3S//TLdsAhzZt5+EeKbIAyJGo5fvf6CpZkGx8JY=,iv:3OSFTHNe3R/tfS/p4114E0xOskG9LEGjrFyNEXSn73U=,tag:YbJKcnpZQB+0Pvm2KCoukg==,type:str]
restic-server: ENC[AES256_GCM,data:uEpfR/uoUOt+1+mi+fly330S8wgpt/SDqZa/qwapjLMDSjcPZxnzOw21qqk=,iv:AwrjUPIoKcNwtJI51LihGGZgAU3t9AQnUfNl52ooMjY=,tag:DCRmcBif+i+7byAdgnDFvA==,type:str]
sops:
    age:
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmNOemZGWnd6UkJNdnRl
            azcrL2ZlZkRBbmhTZ0ZsaC9uK2FpaGV3SURVCmhQd0x1Z3dZQitCc1dWdlpmTFRP
            UFZ2dEkybUdXUUhiTzYyTDJDZ3duYlEKLS0tIFZqaFV3SGtmM1ZrSDBiKzR6VEYw
            WGRRYXVUaDBQbUxvbkVnZm5jcmZCSEUKob7JgfKm3+0KFu2EdrFhf/VO23hwrNnK
            EzIBFQmQDafDI46Cg5tvWmxkzkJT8ygk7RgaguH0jmRh7IZyX+mHqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnVCTTVrVkZnNEhodmpO
            MHVraCtFMVczUWQvbDFIc0ZKTTgrTEg2UDBRCmhYdWJDRC8rWk01MFA1STZwdUpx
            TEo3V2UyQTNrUUlReWllZ0MrMHNrVEUKLS0tIHlsVDI1bXVGenRMWko2TVMzVnBn
            eXFVd3B0dXJQbzg1WlZoTWwxQkFkVnMKdr804la9TK4YBJXTJup+Zwn2Gcdi8lKM
            D47LMA+cIKmzOA/GA4yipuQTzVjxoWXw+yMSSPc0CSGB16vEqE3bMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T13:22:26Z"
    mac: ENC[AES256_GCM,data:8k9i+7vga7fEd9jmriAJKwggislZ0K1e+MYq5+cyxRF6haxamGr1FUJpKK00F3myDQHQsNKDYYxG8GU9I6xfFXquowH6Mtiq48zU/MyJwpRpp34t/f4xVdzVgOp0FoBB2ev1vllCXjQ9eVWIfX5Ta5gX/FzpUZf8EDv+0Uv0tEE=,iv:LhILEWibsDbKddrKGF+xXIJXf6jtYIijbW24YCRhrgY=,tag:4W5zV1nY3Q+0apiSbYnlNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
