placeholder: ENC[AES256_GCM,data:1LB3dVYgQThXoKk=,iv:DvOgeeHX/8YYCZQiu8wD3gV4eamZ0j2OUR6mmKEPmcg=,tag:Hzs1yrrEt+pcDCNEOdhjMw==,type:str]
sops:
    age:
        - recipient: age14dxfxxluxx2vmh9n77p2278vw8t4rk8yxeq3eh2aww46u7n4mdpqx6upfw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OUhPM09CVnVvejR5ODh4
            dXVRdjJRd3lCeXJnUE1tRUx1S1ViYzBxZHdVCldmUWhoelR0NlZIVUVZa3NaVVdZ
            c0wrQ29OdTg5REFuM0xKM1d1RCtWWXMKLS0tIFprWXY2OW1xYk1PQU9uU2hNc2Nx
            aWN4SnRtV1MrZms3bW5RTFhZa0Z0cmcKHu9k+VfPLNfzF9Ad8zgUsXUGVre08pn8
            rn2w2uETWeiw2rK3UtwlyyLDcMAlO5uu3LPdSGp6K1ja5bl4AUhvEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK1dMZjN5YmlvSnpGbDYx
            cmZidUkxOGhrb1hMbC9FaEd0U2ZaTVNoelc4CnBRcDI1ODMrN2lWSDJ4WnRsWlB2
            T1oyaDQrZklTVllmOW1zWjJUYlo0eVEKLS0tIFYxV0Q4aStaZFNYb2FnSkk1ay9S
            amhOUS9YSlRIQVZNdmZvVUhNWlJRMG8K0pdEdEj0WdXZXRytdXGmZPamPW7P1mmZ
            RRpPu2YsQ42x2zaq3TChzHK9YUf/k1f0pwb+OSP8qXgnzCyTJy6a2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T14:06:40Z"
    mac: ENC[AES256_GCM,data:j6/DfD9BADi3H6OsQIJNTryqPSwo5gZyEC7bQnjF34P2+Uk2ugRSy5Bc/EJQwTxxaSMqYCOM1fEiOD12DXy5pWpzcpUS6m+PduNiSM4b3VbWRX60ZlqBjnTJZ0S7UEHHdAQpFNpiATl9enXL4x/sWmPs2j3Ox2RsbjP04vEaf/8=,iv:nctPmP9H8jDcM1ZrqCdwc4Xze1vJNrFI5KcDFzUAfkg=,tag:7eamNNWJwOQFylX538xiTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
