placeholder: ENC[AES256_GCM,data:cSoW+6l0sOUQbeo=,iv:y/d9xkPDXLuYUtvL6xcx8NneLkvVvwVHtYWwp+gNsFo=,tag:P2Yhh4y8PEDrX9LxBxfQzQ==,type:str]
sops:
    age:
        - recipient: age14dxfxxluxx2vmh9n77p2278vw8t4rk8yxeq3eh2aww46u7n4mdpqx6upfw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ2pGWEtFSU1RMm0zUDZB
            SDVtTFVVQjRJWEE5T1FTWlRRSjk0TDV2Q2lzCjJUSnNncmtIMVFpeXNEWkRIeitS
            dmRlZnBSbDZtUlpKVEJtS2ZIVFFXT0UKLS0tIHFzVkVmL2xlbmgvZUx2MFlrTmNT
            SFFNeXdnTnFxWWRyZmwyTUkrOVFkMHMKvly8R269BHSlYn/1FY/sVlc9aQZC1quG
            m43GWSlKVlhzWQAcLmYg3n7Dk7+mOkevEP4PcyIjrcWrEcJhuhEYhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRy8zdkd5VkI3Uy8yQ2tS
            OWVpZUs4cEU0a2wvdC9mNUQxd0NIUXo5Y24wCjVPaWI2OU1HY1NXdW55Tjk0UVZw
            R3JmbmNWZXA3c2IvMVcvZ29FbFdSalEKLS0tIDl6dFNqcXdIUDBVT3g1TGZ6UVBS
            RG5aRjlqWWNOSXMvSnhPcFNaMTZHQVkKXBQ1xYgomsB7mPEBL5qjz28/cCxL//Ov
            uWOmNeKSz6uiKKyKI3bYY4FE4VsxOsG25qg7ecRSPMchj+o87A6bFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T14:07:01Z"
    mac: ENC[AES256_GCM,data:2IQEP2EfEu7DzNKCv7qh9EHNF1B4sqxmXOxCOC+7OvJZuOJ+Wz1jkc1TveNmuMOXKmm7TUDHlANxjYWPZ86baXwEsyIRQwTlzbHsz6T9tnG22Sx9SIlDedAq8YQO9kpqq0AERml/qomJtyUjCWw0gIuJjTPIA5aB1i4iIpZEC+A=,iv:W/26l0mkQDEahZb24PZyfVNRw6va3R7Dazrsa5EoreM=,tag:YjX9ANByAPqfmalpTM8LRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
