private_keys:
    id_ume: ENC[AES256_GCM,data:y5iTR36XClEUzCGuEKOWMuC8jDW0oapBpukQjB3Z6bm5hxr13jibKaKGfIyKsmngzVRJWlMqG03JTsHVNNZo6iK5L1RStrqk6unXU1LxObXl2i48+77puGXsOQGXlW4JyOV8xcU/912HyAudnZ5aYooZgp1fKHCwprxLBu2IDtT20/x20OLFq8/GbEhlU/qfA0qahyH8KOrI8Ts8N/YARRjPk2gFaxZd4QywIRX6idCugQOKsPcs3mefTsuWqQxq+qO2+nWrpSMP80y2mmIsb59WbXcTAK6Ds0ypD1cQGja+plABK+hACnufZqqkKmv9MI1CVq0e9bv0i+5FpqeTNid9ShbJssVZ9KM3A/rsfetOekVNvpAFNufIvweuMFCHBxF5pKfZ6BvZdTSjKl6KnsrlfXear2JNJStPQH3KRW2qFDsEPukjOjwbIpl9LU7dbghy23z+MOZ3UGjYzprh/5HO40GMe3eBQUnqbaBIh41RpVE0bjcUBkM3QA5xc3cbGp45KRFZ3ysxkDXRqWHgVWfMEN9ijz7VFQ6u0RTa+qWqcPB9+AWB2l+qPL2DLexj5HR33Pq9HNku4ByGVKtcGf3ZQZMmaTLYXuYPFkdCOwlrYzHgU6Zbo7laSzMBkA0NDNgZExUiwPLuA8BVXmqd/zUTQTbOQm0X75faU9MMPobKwE8IPG69UgS0QycEjwVYceAdIrSfivWR60GrBfXq9S4GkcHK505BKX4tQ8FuYNCR,iv:tpnZALko2QK1b0dmpgLkk5AFuSZMOK3EqplyvNGH3Vc=,tag:85wXK/tG0JvYHoaji3KvQQ==,type:str]
    id_nadesiko: ENC[AES256_GCM,data:EXcAOA2Sn1eZIok6RnXSSb1o2Hr4KCFOZzB+/f8RUMGxpcT0xA3Sfc8g/D7q8W6qvwRN71gMpY0XvNsnq6Zo595dEIWRNL2tQ2IEilaWuTkQOQpeYGtUizybaHnJ+g2IEO/cL/99mEDdzdG+30VCIDIciHHH5K7XwL+WMcRO23jzF4he0MtFGNAYJ9eu//6ahIbCR/H2vO95qH7y1OYGZGThsOHreAjPsUH6YgVnDUpM28NG8pCIaAVAf/1NyZRrwQ0IpvXphsWE37/1+QEnox1M3Wb2DAhQMkSTV7cko0C0FiNN2vQsBX31x2KIYIBDS3f46EsudVVJyOlfNOw/WEhsglGy1V5ucFsEww72wC7EqJWfpDEoYmw/S6NfuALRJ4FgS+3sz3S989Xb516x012Ar4GiSmQOURnFze3Q35m2SnvlfQQTh7AOVXAv9dhXet2AHbCGNB06OXozZ0cWAX3gl56KUeu8GpYlzwq3ux6ikma2LE9L0Ul4+obJ1jODgQuWXd+pIGFKfCunTKyRB6XiQ22H3yMYy603yzsZ77uvi45ggz61DBf06GiTvqVL3tjqmIXqtJExspcmxgHuJXjoYYkD5Yh8cpMK0BpeUBAfMw1v9NJ2njZsXcpUOZtvml9Su+2xdYlVWfgtVkS238MDaDOIh/y7h/dG9g9hzN5D6X4s458S2sOCQBnIL25livHS2/lhvXJSUpmV9wFfx2hCg6F13naWpQ6gkJ9lOpvU,iv:uMhowM4jwiquhZA6tArgLQ4XNkGtArGw9KEOReEouMA=,tag:UYGL+sB3iuZ1AQ4mHM1OyA==,type:str]
yubikeys:
    u2f_keys: ENC[AES256_GCM,data:NUQ2vd2PMIPqqn7wKqTZ3IrqjeEKWkULnWYPpku3Mz8E0QRKr36WJASKeFHszUkriiOspy8qp/E9MMBeLgBEf2XMX2wcla/qE3O1ESVOGiUyTZTz3tjhWjB/kiQdJd4G1Xf59F2fGX/LGlYiHRq4H3T1dHK9RmLnCfVpQDnpmkRsPGh5gErJQTMdSVeEM6eJr8nevctqKaIN5xGBdnkaqyPPq8uz2OEzPxgHvDFAMooTDrpLRMJiJ6st/748deBMObQF6yK6,iv:HeLh6GcLARF7FbqUEnxKs3p5uKw/ifvv0l78fmdryAI=,tag:o7iiK1coaEZHtf/6PSgJhA==,type:str]
sops:
    age:
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXKzV5RVNuMXh0YkY3OGN5
            NnlaTy9OTHZoNC9TMXVlVDYvaVNZbTQ3SkVnCkFiSnhBaUZFRnVWV3ZLWW1Fa3VE
            N3Y5NThhVUVRTTRnMFZUbkMvZXNTTTAKLS0tIGpJZUx1djI2bXlmTnVDN0tKTk52
            SlpnWHBpVThTc3VwWkxMbS9MUVBLRFkK6H/0AzZ/nRdxsYug4YYbiWlgV+kFmuOu
            sB+LeFfwTrxvFfEPyNAZicJ/TwF+SQM37r7jbiObj51mAsylbzq5Wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age152k4hxe5vyj6kq48w4dqcm3tadyr7f6u02ydgfu8s2uuu478jawsj5q3yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZURycE1icVphcWZPa0Nr
            dWJXT2dzRU95N2d6dmFlMWZhblc4bkRQMVJNCmU5WlpqTG5wZklCcGt4d0ZrcHVt
            RVJPT2Jod0NHY0JpSEpjektSWVhvWEUKLS0tIHZBOEdRclJHS2hRbWFFNVhDa2dz
            YVpEU1A5RlZYTG9MRTdCNktFVStzcUkKCA0fqmAR1323jadFNr40WWtXOFOFPMjO
            3Y7onDgasvPUh1WGuREMLpQojW1eOnWLwgnAFomdnIvND4Ydy4lx3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1se8sv8c084c5hqg8y448yhu3x4q4lw843v7l9dfyt08qaxyh2d6supwezt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Tlord3JBNWdwRjdjcGM0
            LzZSK1IxTFpCVnRSWmIrK3pPOE5wM0UwVEdzCm96bDBFb1VXaEhPeXlUR2pUUDJW
            SnZlNEhZSkNjNWh5OFhXazNxV2Z1UFEKLS0tIENXbERONkhhNk5PeHo4OXJvNVB3
            U3hURkVoaGs0U1kwOU1rTjRPVkVEb1EKNeR3ktYtTJrndEd3FvI6RumfW1I8VtIQ
            CTPVxaq3d4UqwMexjwENyPgNWJd8cklkmBj7fG4LIvXc+RgxX4Acnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l3s5ckneu4reytw4ecyt2qcc49hf8kpx0s89senr5yhf6fqu3y0sxkv398
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWDJiNVplTTNNamZrbGIz
            c05HYnJZWnhRRnZjRzgwejcyOTlNc3hWNG1ZCmkwMGtjRFI2aVlyOVVvWVlNQXE3
            T09teFFSbTN5MGMva1labVAxeDgxaDAKLS0tIHFXMmM1ODdNL1hncE90TW9vaGZY
            bnVSeU83V3lQQk9rMG1vbjFsVUZpWTgKakyFnSWJbPAHsnlrDoOZJzoCPe5aJ5Rg
            0Cc4zth6T5qf+m8nGB+B19zgPcEA5aqco+Xc4P1/gqHi1E/vAccf3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T18:20:38Z"
    mac: ENC[AES256_GCM,data:iO/M9YymoYxW4X1I7vI3yh/4iPsI9Yi5ac7R5WRcyjON5q+OBdsSP3cO/CsauBnuf2uymbFtBmiP4HO3D5XaORcM4C7y5dIXiHcAui/gLkPn190zmry2Ju8gOw0cIsb14uJirc0iQK17H9MSUZ1Jbjitj9sBgUpm99RPmWdXzqk=,iv:9tf79kG4KtYJ4M5C+J+GP3FVbdX3PLFMsBDwsw6mp4E=,tag:9BpoNldRu2hY8IJULWtodA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
