# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  midnight-theme = {
    pname = "midnight-theme";
    version = "6f727783935069c02b8a84985f3bd55a38982533";
    src = fetchgit {
      url = "https://github.com/refact0r/midnight-discord.git";
      rev = "6f727783935069c02b8a84985f3bd55a38982533";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XoYfZdz07P6b7p7DZLiArFG4LNlDghrUK32uQtzvkjo=";
    };
    date = "2025-05-05";
  };
  openrgb = {
    pname = "openrgb";
    version = "ca900540b4a493fd7eaaf9a2425c3874314e9580";
    src = fetchgit {
      url = "https://gitlab.com/CalcProgrammer1/OpenRGB.git";
      rev = "ca900540b4a493fd7eaaf9a2425c3874314e9580";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YySkM9WYEejyMXFpIGPKTQjbepKl50HxOqo7BhWAX5M=";
    };
    date = "2025-05-18";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "b76c16b2b7c465d7b082e11e5210fcd10c6683a7";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi.git";
      rev = "b76c16b2b7c465d7b082e11e5210fcd10c6683a7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9IHENxHQors2z3aYj/xToZD79Gmi1aqlE3QnKnvOT9A=";
    };
    date = "2025-04-18";
  };
  suwayomi-server = {
    pname = "suwayomi-server";
    version = "538bd3f126a5f89aa10a0775f8c894c443dae59f";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-Server.git";
      rev = "538bd3f126a5f89aa10a0775f8c894c443dae59f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LEZabI+LyMpi5dp0wc5HrDI9r2RRrTLjjcd4kIi5smE=";
    };
    date = "2025-05-16";
  };
  suwayomi-webui = {
    pname = "suwayomi-webui";
    version = "7885bcda98a55d9be8943a174e4193ff76da4760";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-WebUI.git";
      rev = "7885bcda98a55d9be8943a174e4193ff76da4760";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wYo2X+72CnZQUimKd5tXWeFGDnbD6/uspWqOjYynaco=";
    };
    date = "2025-05-18";
  };
}
