# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  midnight-theme = {
    pname = "midnight-theme";
    version = "192472d3aa91274baa093a6a9e2303f7c7857fac";
    src = fetchgit {
      url = "https://github.com/refact0r/midnight-discord.git";
      rev = "192472d3aa91274baa093a6a9e2303f7c7857fac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-w/CU5KN6WN0MQBSL2JLzO+qvzW83138lAql1rlK5m88=";
    };
    date = "2025-04-30";
  };
  openrgb = {
    pname = "openrgb";
    version = "6a80f24962db1147e3200815aacec786c1893971";
    src = fetchgit {
      url = "https://gitlab.com/CalcProgrammer1/OpenRGB.git";
      rev = "6a80f24962db1147e3200815aacec786c1893971";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lYr2KNSfQZpjfmKBtgtG1hnwXPQW0NGybzX9pusQsqA=";
    };
    date = "2025-05-02";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "b76c16b2b7c465d7b082e11e5210fcd10c6683a7";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi.git";
      rev = "b76c16b2b7c465d7b082e11e5210fcd10c6683a7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9IHENxHQors2z3aYj/xToZD79Gmi1aqlE3QnKnvOT9A=";
    };
    date = "2025-04-18";
  };
}
