# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  midnight-theme = {
    pname = "midnight-theme";
    version = "91c52e4d056f1b2502ebb3709abb59924f0543a4";
    src = fetchgit {
      url = "https://github.com/refact0r/midnight-discord.git";
      rev = "91c52e4d056f1b2502ebb3709abb59924f0543a4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UEAuqlFqobRlu5of/q5eIqoo2y1T13SSa46DlmGCAo4=";
    };
    date = "2025-06-08";
  };
  openrgb = {
    pname = "openrgb";
    version = "6793d4a3a0b8b6b785d4b85b8af0acd7fdea76e9";
    src = fetchgit {
      url = "https://gitlab.com/CalcProgrammer1/OpenRGB.git";
      rev = "6793d4a3a0b8b6b785d4b85b8af0acd7fdea76e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5crtFhMAJnYqHsKi2t9GYIM0eIZ+deWpZMyKLMY/k3E=";
    };
    date = "2025-06-04";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "fb7011ec48bd065f398f2ff26d76e301aff1dc22";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi.git";
      rev = "fb7011ec48bd065f398f2ff26d76e301aff1dc22";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wwLcb7z5jCKgKPY5mNhYIoPvKbVO3PwULrJ+Lm3Ra7g=";
    };
    date = "2025-06-09";
  };
  suwayomi-server = {
    pname = "suwayomi-server";
    version = "dee61e191c0175c6dae6346f58293e0225df8b1a";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-Server.git";
      rev = "dee61e191c0175c6dae6346f58293e0225df8b1a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FevRd2XTcWgAxI3YgSZBUrJeIDeolbAQ82M8sKTKM2A=";
    };
    date = "2025-05-27";
  };
  suwayomi-webui = {
    pname = "suwayomi-webui";
    version = "20a325a6c282958f38ba37dd1f3e13a8bdbf4276";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-WebUI.git";
      rev = "20a325a6c282958f38ba37dd1f3e13a8bdbf4276";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8Qq3zi8Axbiwqx7mQl3kH0PpvYw3sgzLiV2ivnVIIH0=";
    };
    date = "2025-06-08";
  };
}
