when:
  - event: push
    path:
      include:
        - 'flake.lock'
        - '**/*.nix'

labels:
  backend: local

steps:
  - name: check
    image: bash
    commands:
      - NIXPKGS_ALLOW_UNFREE=1 nix flake check --impure --show-trace
