labels:
  backend: local

steps:
  - name: static-check
    when:
      - event: push
      - path:
          include:
            - '*.nix'
    image: bash
    commands:
      - |
        (which statix && statix) || nix --extra-experimental-features "nix-command flakes" \
          run github:oppiliappan/statix -- check
