labels:
  backend: local

steps:
  - name: static-check
    when:
      - event: push
    image: bash
    commands:
      - |
        (which statix && statix check) || nix --extra-experimental-features "nix-command flakes" \
          run github:oppiliappan/statix -- check
