when:
  - event: push
  - path:
      include:
        - '*.nix'

labels:
  backend: local

steps:
  - name: static-check
    image: bash
    commands:
      - |
        (which statix && statix check) || nix --extra-experimental-features "nix-command flakes" \
          run github:oppiliappan/statix -- check
