when:
  - event: push
    branch: main
    path:
      exclude:
        - 'configs/{shirayuri,kuroyuri}/**'
      on_empty: true
  - event: manual

labels:
  backend: local

steps:
  - name: static-check
    image: bash
    commands:
      - nix --extra-experimental-features "nix-command flakes" run github:oppiliappan/statix -- check
  - name: flake-check
    image: bash
    commands:
      - nix --extra-experimental-features "nix-command flakes" flake check
  - name: deployment
    image: bash
    depends_on:
      - static-check
      - flake-check
    environment:
      DEPLOYMENT_KEY:
        from_secret: DEPLOYMENT_KEY
    commands:
      - echo "$DEPLOYMENT_KEY" > deployment
      - chmod 600 deployment
      - >
        nix --extra-experimental-features "nix-command flakes" run github:serokell/deploy-rs --
          --ssh-opts "-o StrictHostKeyChecking=no -i deployment" --skip-checks
