when:
  - event: push
    path:
      include:
        - 'flake.lock'
        - '{pkgs,configs,lib,homeModules,modules}/**/*.nix'
      exclude:
        - 'configs/{yuri,lesstop,kuroyuri,shirayuri,meow,thelessnas}/**'

labels:
  backend: local

depends_on:
  - flake_check

steps:
  - name: build
    image: bash
    commands:
      - nix-fast-build -f .#nixosConfigurations.thelessone.config.system.build.toplevel --no-nom -j 4
      - echo "$(readlink -f ./result-)" > generationPath

  - name: diff
    depends_on:
      - build
    image: bash
    commands:
      - nix run nixpkgs#nvd -- diff /run/current-system "$(cat generationPath)"

  - name: kickstart deployment
    when:
      - event: deployment
      - branch: main
        evaluate: not (CI_COMMIT_MESSAGE endsWith `!nodeploy`)
    depends_on:
      - build
    image: bash
    environment:
      DEPLOYMENT_KEY_YURI:
        from_secret: DEPLOYMENT_KEY_YURI
    commands:
      - echo "$DEPLOYMENT_KEY_YURI" > priv
      - chmod 400 priv
      - |
        nix run nixpkgs#openssh -- \
          -i ./priv -T root@100.64.64.3 \
          tmux new -d -s "remote-switch-thelessone" \
          'nix run self#remote-switch-thelessone -- "'$(cat generationPath)'" ./priv'

  - name: wait for deeployment
    depends_on:
      - kickstart deployment
    image: bash
    commands:
      - watch -g ls -lt /nix/var/nix/profiles
