when:
  - event: push
    branch: main
    path:
      exclude:
        - 'configs/{shirayuri,kuroyuri}/**'
      on_empty: true
  - event: deployment

depends_on:
  - static-check
  - flake-check

steps:
  - name: deployment
    image: native
    secrets:
      - DEPLOYMENT_KEY
    commands:
      - echo "$DEPLOYMENT_KEY" > deployment
      - chmod 600 deployment
      - >
        nix --extra-experimental-features "nix-command flakes" run github:serokell/deploy-rs --
          --ssh-opts "-o StrictHostKeyChecking=no -i deployment" --skip-checks
