when:
  - event: push
    path:
      include:
        - 'flake.lock'
        - '{pkgs,configs,lib,homeModules,modules}/**/*.nix'
      exclude:
        - 'configs/{yuri,lesstop,kuroyuri,shirayuri,meow,thelessnas}/**'

labels:
  backend: local

depends_on:
  - flake_check

steps:
  - name: build
    image: bash
    commands:
      - nix-fast-build -f .#nixosConfigurations.thelessone.config.system.build.toplevel --no-nom -j 12 --eval-workers 1
      - echo "$(readlink -f ./result-)" > generationPath

  - name: diff
    depends_on:
      - build
    image: bash
    commands:
      - echo "Full diff"
      - nvd diff /run/current-system "$(cat generationPath)"
      - echo "^ Full diff ^ --- v Direct dependency diff v"
      - nvd diff /run/current-system "$(cat generationPath)" -s

  - name: kickstart deployment
    when:
      - event: deployment
      - branch: main
        evaluate: not (CI_COMMIT_MESSAGE endsWith `!nodeploy`)
    depends_on:
      - build
    image: bash
    environment:
      DEPLOYMENT_KEY_THELESSNAS:
        from_secret: DEPLOYMENT_KEY_THELESSNAS
    commands:
      - echo "$DEPLOYMENT_KEY_THELESSNAS" > priv
      - chmod 400 priv
      - |
        ssh -i ./priv -T root@10.0.0.6 \
          nix run nixpkgs#tmux -- new -d -s "remote-switch-thelessone-local" \
          'nix run self#switch-10-0-0-5 -- "'$(cat generationPath)'" $HOME/.ssh/deploymentThelessone'

  - name: wait for deeployment
    depends_on:
      - kickstart deployment
    image: bash
    commands:
      - nix shell nixpkgs#inotify-tools -c inotifywait -r -e modify,create,delete /nix/var/nix/profiles
