when:
  - event: push
    path:
      include:
        - 'flake.lock'
        - '{pkgs,configs,lib,homeModules,modules}/**/*.nix'
      exclude:
        - 'configs/{thelessone,lesstop,kuroyuri,shirayuri,meow}/**'

labels:
  backend: local

steps:
  - name: build
    image: bash
    commands:
      - nix-fast-build -f .#nixosConfigurations.yuri.config.system.build.toplevel --no-link --no-nom

  - name: deployment
    when:
      - branch: main
        evaluate: not (CI_COMMIT_MESSAGE endsWith `!nodeploy`)
    depends_on:
      - build
    image: bash
    environment:
      DEPLOYMENT_KEY_YURI:
        from_secret: DEPLOYMENT_KEY_YURI
    commands:
      - echo "$DEPLOYMENT_KEY_YURI" > deployment
      - chmod 400 deployment
      - nix --extra-experimental-features "nix-command flakes" run .#deploy-yuri -- switch deployment
