when:
  - event: push
    branch: main
  - event: manual
  - event: deployment
  - path:
      include:
        - 'flake.lock'
        - '*.nix'
      exclude:
        - 'configs/{yuri,lesstop,kuroyuri,shirayuri}/**'

labels:
  backend: local

steps:
  - name: build
    image: bash
    commands:
      - |
        nix --extra-experimental-features "nix-command flakes" \
          build .#nixosConfigurations.thelessone.config.system.build.toplevel --no-link
  - name: deployment
    image: bash
    depends_on:
      - build
    environment:
      DEPLOYMENT_KEY:
        from_secret: DEPLOYMENT_KEY
    commands:
      - echo "$DEPLOYMENT_KEY" > deployment
      - chmod 400 deployment
      - nix --extra-experimental-features "nix-command flakes" run .#deploy-thelessone -- switch deployment
