when:
  - event: cron
    cron: 'update'

labels:
  backend: docker

steps:
  - name: update
    image: nixos/nix:2.26.4-amd64
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      CODEBERG_KEY:
        from_secret: codeberg_ssh_key
      NIX_CONFIG: |
        sandbox = true
        extra-experimental-features = nix-command flakes
      NIX_DEBUG: 1
    privileged: true
    commands:
      - mkdir ~/.ssh ~/.secrets
      - echo "$CODEBERG_KEY" > ~/.ssh/id_ed25519
      - chmod 400 ~/.ssh/id_ed25519
      - >
        echo "codeberg.org ssh-ed25519
        AAAAC3NzaC1lZDI1NTE5AAAAIIVIC02vnjFyL+I4RHfvIGNtOgJMe769VTF1VR4EB3ZB" > ~/.ssh/known_hosts
      - echo "access-tokens = github.com=$GITHUB_TOKEN" >> /etc/nix/nix.conf
      - git config user.email "hanakretzer+autoupdate@gmail.com"
      - git config user.name "nanoyaki (autoupdate)"

      - nix flake update
      - git add flake.lock
      - 'git commit -m "chore: Update $(date +"%d.%m.%y")"'

      - (git diff --quiet HEAD $CI_COMMIT_SHA && exit 0) || echo "Updates found, pushing commit."
      - git config core.sshCommand "ssh -i ~/.ssh/id_ed25519"
      - git remote set-url origin git@codeberg.org:nanoyaki/flake.git
      - git pull --rebase origin main
      - git push --set-upstream origin main
