deployment:
    private: ENC[AES256_GCM,data:Y8+QsYSlFau27tGrSKd/gj9RDHwBzAkvy9GyOZOanRaLnES70z2AuBpvJmn3BOcgMxojjKWTudqfqi26dxHiK4ZCIiosQv92y+Q97z4YCLWH7SaLB47NbJYi30Zj9lG6/q3S2h609iYAiyCw65zynfIA3C6u4aj9fRsijLSWu05UpB/ojsB8uExC1kCEcbmDs8WTdE634ufIZlSFtiieH663srYAdcd63jsoqfNnFjDukYik+v8NnaXD+BtjDVgGKU3FNTYCVT46yY+Hn1kZfCrtbZ+VU3sGBoMzTFe2G/eknSnc7/eTShj4Cq+9eE3YYVuSe3mSYxziX66hBYff0q4cS9YVJovSE29fGadhkULWgLpN6B4jJuSJXT3FS3Ki9Dp7fG72EHLr32dAt/Z+hwyoQAlgqxQ8D7/WH4ulpj6FXhvOYTidQJF9NrJide0TB7KnGX0JgSRKmacfYZedBhU2NWdrdp0gXS43n9JaftoYiLupEAsR/ZuJ7dnOTS5goi3/EdpmHYIwWIKPsJUGEdq2UhAwmjH94adt,iv:3aKPnU5z35lVIf09bj/fhexs19frMlz88t8VteMgyFw=,tag:RUVcN42pMyNRNbVY5QRJng==,type:str]
    public: ENC[AES256_GCM,data:otAThlt7Ak20mqgnx1tP9p6JN1jPKzXoAMRANYpmv+JqfehwC1PYK7juxNP00pUtU4PyTu+FAFbyvshaaj0WiuiImGFLU4W2IYSP7AIqgHg=,iv:n04IrynPEJHvi1Z5pfu9pVRzL3AmOF5MhM9Q68DvCDY=,tag:KTLfoGfxbx+b8+8KR42w2g==,type:str]
syncthing:
    cert: ENC[AES256_GCM,data:lDIRaGzopJ9UaEY6tCV0AN/rGY8wKYyQk/nY+EoTkRU2NyKmVcsoa5hDNjgM7a67UfZPfczvSVcRcjPLzuupmnBqK2yh40rRTChL3PT9okc4JEqkZlSojX136QCvISN3JBZqaach1btP4t0CpYxybSjaABNIr2zMhDsdz2yMuXF20HwscyYyJAOMLyw8DH4z8Gb0BhvJ0yBN6RpPNAQpSCy1wIEaVvUEm9V2osrBDRXUkkrNp3q65loAIHcZTXrEMlST5LZv99V0MPneyV3RQfoBqw/c+QokC/jNRFzkcTmaXSxvjATIyFnHvORBBEd2QzUsIkyiKkrWAdCql/XP8wdBeau2HuA2ntJalZSgLQEK725oLxMoq8heP0OTz98M+V5bkkfYJO0qFQW4SyV5jw8r78vtPWV7hK6QglE8K5K0i0UmQ+fImCbaamR28Xd6nc1HN/7l3l7CFDMRBNFG/7BxWvEpRmPV/AOkcPM+mrOcZLOUArcn6pZdj+DTG1FHNS/t+2fW0GmzZgqu0T9vrEcjcLsyuaFcCgcCi17xQeODJIApRYuC2uOhSZk08Zn1ROElyaTXpi44oAh6vWa83qt5M+ZOFZl8Juk7hG+eOAIFUT+uzH5pmglTqQFL2kgFaurKhNmtYdWDLPlcPT3w+CGynCGNAieV13hhFoec0vfZtQvQsDCp1spNCn7Y+PO6iMg/6tKuVSNOg1gXR+KpERsycCkaTZuvMXo7EKibdJ7iRpOKdvfNYQv6+LuleLkz8oOWySOgfi+enMtxQOfJVzy9LzyQF/lh6UVkCBSZBy8Vt25UU7RX7vs6NQgljYRuYumJOdrwC2m4tfOxT/GU7Pl4BJXtyxhHcFFjfePgbKdlrDl0Z/yHcQnRla1l3v5wN91mfmdJiNe0J31lOO+QM5pnppcKdTGSwdlUzVbfTvMWV5PV49TZX29o83WcEOBvz5T1QuL+iPIE+K+9N5wI6k035eg4FgWasWAjEClyf0mgQg+lnJK2mARUa0ZeiKQgmY0cH10AlkR5hHKI1/Awix/6tbHXTfCvttc=,iv:QqC1MeONhV85FSDMt8TB3R6NMMUncYmba6E6IA5LHok=,tag:kpB+BDbtl5pZjISUGkZY3g==,type:str]
    key: ENC[AES256_GCM,data:pzOo2DtrkbB30YHY5k/RzTvoiK/5oEk885XbGUmeE2bM7xy1ZtEVjnOQY1bmtSOPZX4M44r+854osTYqPzC0SlrsVDu/8HzmRfVsXu5hAf9jNcnt3OwZfAp/SvYwikUNwMD1Gwsn5W/vhtwQyzkCJFselpL3K8orSV87W6WBEIxYplHaPb/QYIi2ilS6gdygQnZ1rvmxL3qAOUppqNd8GmF/9wFk4kNkFy3WiW9HIffP32roggncRtwf92APdAJ40zWfD9i5WEMhrM+7KUoKVWWTlVPiLMhTJmx/rP1wpUB5Rjy0xqbaM7ZEWPbkxFZ5pY5lHIO2fGG+DyjifZ8ArRPPa4mQMl4FWGMkQ3KrIlSK0OmTr0lqD4JcLiMs4GPv,iv:fqIanlp9kDovPA1yZhUijejEcF+j9imPaltaPrYZbdU=,tag:62Rg19wURWqwWcmcp0aexQ==,type:str]
dynamicdns:
    nanoyaki.space: ENC[AES256_GCM,data:Evj0uF7TyrXQOHh9DW6W7mFV5YkBfR4Y4WW9D9+BfWQ=,iv:xKjsukzEQStLidAYvGDaO14b3c+gxAPGHbADwAi1av8=,tag:Thkm6btzNu9cjTSJ6iJ3jw==,type:str]
    theless.one: ENC[AES256_GCM,data:U0SdmkQqVzJ1O2HVpLgk7ogobU6NJIEYiRWNCs+keg4=,iv:2m5fZoFZytsn+LqkXVMaR1/b3DFp7hmOxaVsvjAdI6Y=,tag:5z3YEpEdEEUwdH5EGeE5/w==,type:str]
woodpecker:
    forgejo:
        clientId: ENC[AES256_GCM,data:Le6xv1zoVFF1HQzVevy43oCsREnCIbmb/sFOw/rPhp/YxV11cLwCVkv3FSsrfiyB+3on+E8an2iIjSH3ad4=,iv:sPj8DClTSaKYciMmMZtuTguWwE25hL9xmvuI3Jiz248=,tag:OKRGxZF69cZ98LgjX8F9Ag==,type:str]
        clientSecret: ENC[AES256_GCM,data:iIOAATpIOhjkF0J/xPlWdLHy5/bYkrTACXktjCy7and7Gn/TjbWziDh/bPJch9d82mB6OCLuwAhCCI+5zIc1lIMIoL0eh2LUJS/l7oTT308bXw==,iv:w4h0TEPQOFWfZnqCq4Dngok/Gf6ErHSsYvw+XU+YPrw=,tag:K8rQod9lSvA4ggbwhmu6zg==,type:str]
    agents:
        native:
            secret: ENC[AES256_GCM,data:zxnGOm0C8pToTYZrqBkV3yQu9V+sa/s7Hd5qAMNcaApCAVXUPxnhQ4WfZueCQSHMWv+nJ0fUA7eSrj/8t5hNNnEFitIwQo+gDk8w0fnVuPo=,iv:+nuJfJczdEIqikP8SYY/fdUkmC6/l45am8VAY+JsEOE=,tag:ykA4RZBXr1+9fPD6uhI5rg==,type:str]
        docker:
            secret: ENC[AES256_GCM,data:h+0XaqOk/4bsBSWMhsqvEthpDb5PsY/C32hENDMZd9qCqdRAwAJhEBZJ0PnNjD1EWHcGGcTTkdgN9RZmvBIjk/3DC5/M8dLlInnxGUaer44=,iv:L+DV94io7eiYp9rJic/01+ZxnIo1Il63fCSRfnlVod4=,tag:inmiPkeDHtwo3rojMW/Xpw==,type:str]
forgejo:
    users:
        nanoyaki: ENC[AES256_GCM,data:YVeOclX7YwlhyT1MhHJ5U16skfnqrtYKiKNwyxOuxAx//UxWmln8hWW7fKrmRYuTXPaSFwVA+sSCDVVog2POAc0sg3V0qP9oVcto8B7t3kUQke4sz0C7jioYVBsionDioDvBPf0sqxWlh7VrlROA+w0ZuPH41YYUKyrKHosJPjY=,iv:QQVm7QLrf0VdImVXy+kh9o9WwJgVdZs1fIJ6DRWY1Hk=,tag:E02TGAxp3j/0TihGjwv6bQ==,type:str]
    runners:
        default: ENC[AES256_GCM,data:H9dNbIaNUBFuhKBS3wtANRckn5OhtOy6mt77s86ICILQFX5EzvngRdukPnWPIg==,iv:vUw2abErkfY321CGir37fqs38VTy4Ql28+R0IUb596E=,tag:GYW6S3OS9O1yvxG7mNZo4w==,type:str]
caddy:
    users:
        hana: ENC[AES256_GCM,data:p7mNUnC+kMRRZA9vQWfeX/BNL6fecMA/XQLCEgt2HzAl/Fd//yeuJApMeFwW58bE8FnmE/clQH0QvBLaM6frtm8=,iv:WHp/yOKNACcyoLtnsgQ4YHCILes9AJW/K9CFN48B3G4=,tag:sojUqRFE8HNJvOktGthdxw==,type:str]
        nik: ENC[AES256_GCM,data:J2r6bikKQ7ak4DCL4RNkCs/pvL2Nv1RF0oVmKd3WNY0+JTnpkepqCYOMD+dwGcvMqB4rnOfQxOfO7I1aBGOSVw==,iv:0EJ7T+jPQ0SeIlbRWo+L++rmjaEq0zLvpJAuMGodFCQ=,tag:pX66eOzO8Oe8cRE3BBCRuw==,type:str]
        shared: ENC[AES256_GCM,data:bD9QbDG36kXBYLXUGyGNr3MNOXM2HwpX5gTqQCthqJldq16gov6WYrGcvOfjjJpa2YnjhpB7izB43jKAoDtn9SE=,iv:8bY0WLJrySrIXAJyYL6aBu6/epnIpMyWQOvnj7edhUE=,tag:NIdaBzApp8NneNlE5mtnng==,type:str]
        thelessone: ENC[AES256_GCM,data:LqN2kRGXkusjkUUhQK5rOavI5btoVxkr1O3LfiPMDjvf7f6uQZPKrmKuMLXF+QjyIb8CGgkSgjRSMn9OpCUMe+5fwz6SXWQ=,iv:sWFJXIlPFI7VnO37IV7eBqqWIPUkzURX96ERLBoyKmM=,tag:mI8PC9SbGpo5JuCx4LUyrw==,type:str]
nixos:
    users:
        thelessone: ENC[AES256_GCM,data:KUbddc5YmKDzufjSskSu1daEykecCgLUvdNzj3j85bNgVX82on1Uufhg+JFZw0Z3QFliLeIi1PFHWMZeSYsPF2m68KhrO/vI/g6X2X/wxW0phhyKQDORfyMprg5bMX4j94TL/jJzsO/oUA==,iv:NG2Vb0cETkVG2jjD26iDXVR/4lIZuYSKQTjNsmwtc2Y=,tag:nn7+6e2Qkv/UJ02m+0JPBw==,type:str]
mullvad:
    account: ENC[AES256_GCM,data:KIR+jrkruUBCwja3Kgxgtg==,iv:SH6lsFikIK/2kDHW/ZUjrDrV3YK9l6EG9tZkqrGwfhM=,tag:cy36l+LL6xH6vBb0b9MzYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t5w4gj3d8ulk2xud6kgkdpgtugcycd3vqeu05jth6wcflvu3fd0qucklu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SFFKa2VRSmhzM2Z3YzBR
            eFNZUGkzMUR4cTNaRnJXbDk0K2RHMzlBV2tzCnZOdVlSUTR3UnQrcnVUaDRCSUtB
            Mkhvbjg3UWpmb2VnSCtOZXE3dGhzK0EKLS0tIGNNYW45alUzUTV0ZkVDZm9jOStW
            N1lkUnh0OVlTU0hHRUNaMkpGUFpYL0kKGA8oJ5b2iDLZRbR6xUKO/F9t002jH78p
            dizD7RAUIzAe+Oe/99J58fFIdYf7EQ1ibQIkyQxcRhvJGbbLHbvftA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ2FtaElDMDBsNWZNOUhE
            VUo2cGNUd2t1L2huSitjMG9QcGlSdi9rdzM0CmxQbElQcldzaXdqMllQNFhLNHF6
            OWc0eWZ1S3dSbmxPc05VM3MwZXJSaVUKLS0tIFRQc243ektVM3F5anFsUGM5TjJN
            MHRYV1kvZ1dDR3pjS2puRzlOTGhhbG8KNK4FV2LRan89DUctKdaYxfrNL2NSzUAB
            In8Pgg9Ym9NbGEDIYAJJaD1j5ofU+1uP/J7GUN7FSzsZaB+7qQGmxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T01:10:29Z"
    mac: ENC[AES256_GCM,data:vs5N9W44aDuTSVh+lUWCO7F3spe+YCpUHWQ810dfFSEkjIM+CpY7rKvi3ZsfNyi7D/R1W98mFoBLYT6KOuudJXJKdCe1deuUvy+qZWZw1hxYI03j5Ola/7Hekt5lNWf6BQs3D/39iBC/FW3mI7U/ZlDmZUPJhBow7X7zECGzucE=,iv:89ASw4LgRkGpPaCWuY+cB5ue5uYQ0MtUtmTMKwWePcg=,tag:CsLrTMYgs1rRZKqsnZ6VWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
