users:
    hana: ENC[AES256_GCM,data:9oBygdYkn5qgGRQnL0QWwdliH7rh25SDP1cY1vM9FxGCLOod1tjvWTcfe+LbsCf4VZRLyyHD52lnRu49Wc8o6WXJe7wyqlqQNa40JXkeH7LAVu2Hde4t4vN76hK44cczV6LWJjGdliwezQ==,iv:ftQdHAXRbDst7m8b7QYgh7pKfE6E7kUxf+4g/DYJD9M=,tag:kla55BsHWEyS0Ucq9/n5sA==,type:str]
sops:
    age:
        - recipient: age152k4hxe5vyj6kq48w4dqcm3tadyr7f6u02ydgfu8s2uuu478jawsj5q3yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RlByaWRRay9RTkpWVGMv
            dEM2VTRtc0tCRlZDR0p4cmdxNnd1WE84TG53CmppS0dtSUUrWjlMSjlYNjF2ZWRa
            c3FKNUE4QzZZWTMreENJcjdETWg5dW8KLS0tIDg1emMvN1RUNUlFOEtJVC95bjVo
            azQwZGV3cGEwRGthRytqZzVEdU5UbncKmoA/gVAzaY+5jgRP4U8JTnkVzHS9dCro
            jURDgBFYna95Hcf5ms34xjj8o6wx0oO7v1qj6eBfp4/AO9dTqA/JyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0MwNW9hWEtGYVZQSEtm
            SWsza0pqU2tKcTRFV21nZ0F3d1djemNlQmlVCjBaUHdvQmFqMUF2WG9rL0JmeFpM
            QWpCSFVYSjZ0TFpKOGhhOGVBTlBUcTQKLS0tIFAzNStaSVlMbFJ3bVlOZUFwQVRG
            T1JXbnF3MlBUNGYvb1d2VGxDTkVDZnMKsnzJqVNSoBioZ3g782lJ/XVkBgjR3VVA
            HARAEOnI9x2CRcPnc79lMFYlSfRb3mVD5RFf0vuIeEK2TzvZVZXy8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T16:17:37Z"
    mac: ENC[AES256_GCM,data:F7q2/+F3snxsdzhkU9Vn9qU2D4luZwA5PL7DkfWc9oI+24v/LDqL/wtIaWmf0eyr2cVXV3CfHBaADjPRcnPbl96Xfo+ize9ql0BxCVtELdWTtFhOsSgb2w4ThogKWsSqL7bwUvSMEK7uet6oQcz8Yq6a2eBfggENrDAM4JRoKbI=,iv:diuHrGWh1tNFT/OXZzzzuQxSrAVJNTzOpJxU7KFsmz0=,tag:xA68fA8MU9v7OvJiPOS84A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
