users:
    hana: ENC[AES256_GCM,data:9oBygdYkn5qgGRQnL0QWwdliH7rh25SDP1cY1vM9FxGCLOod1tjvWTcfe+LbsCf4VZRLyyHD52lnRu49Wc8o6WXJe7wyqlqQNa40JXkeH7LAVu2Hde4t4vN76hK44cczV6LWJjGdliwezQ==,iv:ftQdHAXRbDst7m8b7QYgh7pKfE6E7kUxf+4g/DYJD9M=,tag:kla55BsHWEyS0Ucq9/n5sA==,type:str]
syncthing:
    cert: ENC[AES256_GCM,data:AHBYxraGbGrbm9GBAkzsmdvWF46zs6kRzYi2ltiwqthwgTtMNJGraEEj+MDMej5z3JlDi/X2drMtJfJSTEPcwjCFXNfl/Eh2/7QGKLvLvVE+XgFBuvNdQaMNb2QkmOKA6qWJb3/ZFJdHneYuuss9n+oH+J8HTPjXFyNIsYuNhmvgqjzLkc2sYaK+TiSkCgP0sVEQ3BFIx8jTlDXG81i15rmOkBmtbeDvCnCT+J+JPtmd3h4a2IIFTPBJ7/kroZXU9TyfXo+eZ8lclpvllnskcw8aurX6GMWCJQ0+xL7gQQywWhaYVNMUtpA4g3i8Iw3k+ekrYhQgwkawg5/PTjJk1i0qXQW3FjJaleGf/vGaAOCIaeZ5x8V7xXIk7isX9YarUNqqtgRs0aJrv6EDxw+VICYsa5aYr6dxDepKMlh0g9c0D7rLONmBBD6qxYfSwiN0h5mK1T/l+SiUr4FvXujhEjgyoaWyg+iqQLCKCSEndlN0xNBqpTknsJ42pOG0lytpk7I2whSp6UNUTHd/RfJCHBHCkyb9qyt9VaYaIvwkr/pO2FDQKa3e42nOsCsPlo3uBgCwr9+TLozkAf+gbi3YrigjpTcDsLtqXN6NOOtgaYuPLawZKCp7LnteaZYC01K9VCxSx3Me749SL9EXwaqoppveCVsgXnTxtSph8/4el2wm3v81DImf8yPx4JDMfeRHTL0fF8zX6s/pVPfeLbPTt5gy8eO1xl6xEfbQrVuIybd7Gonz8KEqvCCjrduY9c0yFVMs7U+X5xgcpL+4fTS3+wF+Hwo21B7z6/fr6N0r46yb2LMFGYClYxuPHEe30i+z3btwONQCti2rawW/CKdqnewwVjK8EB/7Yge8kGkaDD3QAmJWMTnM2ohjkQzOZjCzRQiZwupih6qdr0FTQ08dUa1jYvOJqUcTLA8VmHoNS/Ck9EeoI0v/bkmFXqhtOLauss8WHulR5skt3w+FHeI47fztirkhF3AW1TBJb1WsVsNo1+uFdzbyE6PaQ4FU7TnCqv93yaH26UiGFrlbes8furgQDIm6e82Wf+A=,iv:CX+mhhbg8TfKeHHJ5BLwGcp7E6iHnfldpife5QYyRgc=,tag:qDg+NRBOlxhs0+57R7l5Yw==,type:str]
    key: ENC[AES256_GCM,data:toX3f93XnGOieK2Ab2dgwmfAiSNsB/a1hCYfTVg4cyHW27ZvSVymun2l3WgPETkuPapz3B+Xk8FTjhwMmRhz+BW7M40vDwEytYemGHuK9Il2I9kcXRvfcaZpYAyMzXMNwueKcLMvwMPT7HHCo77kNgVcQU9X3l7RNC/ocmmfXr7/nM6TLpfnCtxjs6Lh0YfzfWjjqVxVT6uzrwA5Cyv83V4IoysIGnDhI7MS+cSCBSk2fKSTjovLU3FoJE6n6jNTsiqb+A6yQGvT4+MKGkfMkT4qNAOiAEWRMHtCNftYcgbP3m0vKL+5ICE8irFZdwOOVycJXS6rTPy9qBnHChLHJtpI0toRFpAD/Rh34pBi9B+kqYL3b3lf9+10159SAGNG,iv:v87Sv6hqObj3knv1W7PBNiB7xRhJmI/jNifltAsnm30=,tag:Im6Fn+XiyA4w2v+5KjQJhw==,type:str]
tailscale: ENC[AES256_GCM,data:iVMCGsaoIn6hgw600Qv3cE76HIomyLeiKSxTpkPMuma3FIx20YSwEBeiAEMZ0iJl,iv:C4i3bBXobH6DCOxUGnQRDNLtoQRaI2VdL42Dzm7iVrg=,tag:DTDdm+b/6X3DgLGXxk0F6w==,type:str]
sops:
    age:
        - recipient: age152k4hxe5vyj6kq48w4dqcm3tadyr7f6u02ydgfu8s2uuu478jawsj5q3yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RlByaWRRay9RTkpWVGMv
            dEM2VTRtc0tCRlZDR0p4cmdxNnd1WE84TG53CmppS0dtSUUrWjlMSjlYNjF2ZWRa
            c3FKNUE4QzZZWTMreENJcjdETWg5dW8KLS0tIDg1emMvN1RUNUlFOEtJVC95bjVo
            azQwZGV3cGEwRGthRytqZzVEdU5UbncKmoA/gVAzaY+5jgRP4U8JTnkVzHS9dCro
            jURDgBFYna95Hcf5ms34xjj8o6wx0oO7v1qj6eBfp4/AO9dTqA/JyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0MwNW9hWEtGYVZQSEtm
            SWsza0pqU2tKcTRFV21nZ0F3d1djemNlQmlVCjBaUHdvQmFqMUF2WG9rL0JmeFpM
            QWpCSFVYSjZ0TFpKOGhhOGVBTlBUcTQKLS0tIFAzNStaSVlMbFJ3bVlOZUFwQVRG
            T1JXbnF3MlBUNGYvb1d2VGxDTkVDZnMKsnzJqVNSoBioZ3g782lJ/XVkBgjR3VVA
            HARAEOnI9x2CRcPnc79lMFYlSfRb3mVD5RFf0vuIeEK2TzvZVZXy8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T14:01:22Z"
    mac: ENC[AES256_GCM,data:65IyubUxSENagri6ggT2E3RNX5gRRP4o69eSLdkAu9fnrMWxssogBV26lijfb+P4rlKtDYlMMG7yB7bmq8kdYetn8OOkqfZpbQtYKrOVccWo8jmWJXBXSQ+8nhKr/pHB5hwf9VmxGTlvW1kj0mNe10yhmVDgFtWVUqzgCqjTjqA=,iv:u+NFxK3uiDGxk0TjxVD2tqJITZeBfeLUUZsCZ0+IQ6w=,tag:25IrvwN2Bi9VesE3sXNDDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
