placeholder: ENC[AES256_GCM,data:e4eKsodfYKPWKSw=,iv:i93yeLljALlLKpF/S4Qb6PsTkhbiK92hgRaAUGuXc/o=,tag:HzWZsWyLbb1FPnJfKa6Fvg==,type:str]
sops:
    age:
        - recipient: age152k4hxe5vyj6kq48w4dqcm3tadyr7f6u02ydgfu8s2uuu478jawsj5q3yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKejUwU0JwMnN1aDM1N29w
            K0ZhOGd6YXNBSVRNYzdoTEtwYndBZGpHSG1rCkpQUVpBd241cXhjcXJmeGdBSEY0
            MGxYTHJLUUlQSGVoMm5XYTJPTjRXMlUKLS0tIHVydWg1dXp4SlE4VkhySmRYYTFJ
            TTU0eWFudVhpQkxXSmNMYzBMWHVJWTgKcdN1d9ay0RPq66C6+pBbiq6HdRM4egiT
            1R5QVKuqY13ZKGGStqG7emVXqYfNBEH41PS7RGI0g8UT+ZXTMeFgQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVnc5bjZ2Z01wMnI4WUxT
            T1JzU3laRk1XTXZicWs5TldLeFBlMTROQmhVCm9LUk96S25FV3dlRUxGOFpQUXdX
            UDZXejVJMVZHek1zeDUzVkVYeks0a0kKLS0tIFZMTktIWHJQQVV2T2ovSStEQXFB
            aFoxcFdmckhjSkxkeHUraGg1NFAyVTgKaVl93vJGYlEaB5MHebbi7F2Y4/NZ4kIm
            b6Z+cu2VzgGrdKdQAPk1YgBR1Qj+Z8OyqB8ZHMERrbfRV8jExNtBxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T23:44:41Z"
    mac: ENC[AES256_GCM,data:m4w9FWyXVyrclXjgUMZBz361C2RvfEefE/H+XX4Pep2GAsuIb1h5OW65cbFNZ+qBzHKiVUxYXqWhWN3eJq+hUwg7NJx7JGSTd8ehfwsgVEfNa6ooyMfHoI5/1EBuX19kjeW66vLemliuAjfVVFKJwMUjW2EDRDUW7Z62jE1LG1I=,iv:SHFQBVlKCh9kQUMeZVihCNoVNPWS0PZcVWMYSA05bt4=,tag:SaB3ajV7NDsrnZDOCt8W2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
