placeholder: ENC[AES256_GCM,data:OrDGDRWHVNC9VtY=,iv:2c2IrLGDKZTLo/ONZQegFYeEoU+hMLxYeCtbGBt/MmY=,tag:PQ04G1uLuqL+w+X4Wus8XQ==,type:str]
sops:
    age:
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UkJQNEJqdUpiNmVqZmV0
            V2hzUTR6a245bnFYUnB3bWVUTzQ0N29WOGxNCkdRdVE0MWJFa0FxU1ljOXV4WnN4
            ZkdYQW5LelVpSVhvdG5NM2MwVGpxS3cKLS0tIHExTGFRMjlQcmMyemhtUUp3cHV5
            eXdBR3VFWE9nOWdFSXI1bldWWDZYRTQKz+ekYKPxyaoCUOhbZU4+wp+4zu5S2zl3
            Z+H9LV9ZQk93wkNlLAVBg3G2JIZzL/PWaOR0wcO3dBhejoCAlar9Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T14:44:33Z"
    mac: ENC[AES256_GCM,data:wBR9ZHHMIt3T1lseA6EQojZUhMPXnZT+ldEeau0BXU3KW9z6W3ofUC62AJ8iSvsZM7VcePvHk6fKNNs5951fEIR0rnIUeSpsReoZJLz+1ju7wxyKicwAF3CLbCikI3LmkDIg6TxwLPWbh3TwaNDxv7JhprFntEDb1FMwYd8oJSg=,iv:IqKsifIulMqvslNxP0YRcpdUpZou8hOziFxgAijvWdI=,tag:fpI7bqG7ptLpAeMliWT3QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
