proxy: ENC[AES256_GCM,data:e8MfY6XgTAD6VgRi/X0BDIiyX8kkJ51BHuGmlaoUUELLy7cbFpDybz2u/Hu1sCvjY2sIhN9FPTJDwagbDkkSrA==,iv:jqqcJ9lYMbu3+NffrouRMn6zOpKd7/921CUjCRsBcTM=,tag:q/wSjlHD0vDQRprWjlYP0Q==,type:str]
bot-token: ENC[AES256_GCM,data:pCAdNw42i549wdwCfysUmOtvD77hJx72luA5N5Rhc2tY55cWqSVqpee7mstbFg9xY3HGhzquYqJ85bTnH3EqNPE1qFz4bEO4,iv:rTRsSL8h4RRtP2FaWPjQVPKaJ5KZiVdmYoHmYrI99/8=,tag:iIkFcJm81wvNt9w7qcV2mg==,type:str]
sops:
    age:
        - recipient: age1t5w4gj3d8ulk2xud6kgkdpgtugcycd3vqeu05jth6wcflvu3fd0qucklu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDd2VytuWkF3K0J2RzR4
            VjlTdmVlc2gyQy8veFF1bWRIYnE3ZWhXSVdNCk9teWMxR2haUEdHQ0N1c1picmsx
            SEJVajdlcGYyciszNVZVYWZGb0lTVUkKLS0tICtOOU9EaUhMVVcwZDd0WlV1QVB6
            U3Fkc2hoY3Vja2VEUDRMcERtdzdFdWsKIa6p7Roxs201kCRFP+sS5X81luOuFv0U
            sZ1tkblo/LHck+K4QCyM+2nUKSsLALSWmqaWCWZdTgLoJlQ3YdBd9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZjRXSkJMUVRYNVpmMTNk
            MkVoeHNEN0FHb1ZGWjBJN2MzMmNjRGVzeHhNCm8rY2VBVW9WYU0zcGFHcWdRUHZl
            UDNkeTFYN2lwWmhTWllSOTRoeTdoZW8KLS0tIHlSMEhkMm5EREVoZWt5M2lBOW5B
            ZHN2OXNkOHU1ZklIdHNkbGpOcEJqMzQKajGBOwG/iJ++bhpk+tjPRqDxkEv202YP
            RWuFDoq4xHDmkk2JDXDnTMAV0jCEKhW2MYp/hdbEP6Hkvler7bNqWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T10:13:15Z"
    mac: ENC[AES256_GCM,data:GKn6f3u2ivblN3vfwq+tbU3e+YhvlnwT3Bq8D+X6UumOdCJGowglkkr8E51bsm7Cz8wrEMv+AaFw61WbbOU3NwLv0LBbI3T41cAHJhHtL3mfHRvh/oivHefYust/wPo9iKz7ZaFvW2tYbXsm1DlezvPl1M7OMfK88qkWxd4N8Kg=,iv:y1b12YWJTzMKak0Fce5uIwXhi0DMN9yhp+SBNUAbPNU=,tag:yn+wKo8GCM9FKGDsby7mcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
