users:
    admin: ENC[AES256_GCM,data:LrRMXI07yl1MMetSDdwy0wPhIoXMrXvZBeMN9x4PjexLI130YrzZCqbYWvuxGArxC+5kg22XC9Xe7crNXTQS8YYn2v7GTOF7JQ==,iv:rHI1/9M/JnF8TB1ieXAZ6segUQhgdyQPmRdfuJeXdBA=,tag:a6mA9JDK9fbqh88GMZyfiQ==,type:str]
deploymentThelessone: ENC[AES256_GCM,data:RjU237g2WiacFK8hyVlP+PN24Z2H2Di9QfOL1KRJmXIiG8KHQraV01ZjOasKkARbgWcVj2sYW0G4GQVo1EpP9iksKR3AzLShg9lpBS/8f1tV24qS45N6tlhMk7hxDIiwoukFCbxEJh/tSLmD+E9stahD3K/k5M1PLqKI6lfKugSxmmRzkb3Fgwesr4bHa7d5qDucl1k6y9BKkRp+rfmuVEwp9XRsSvB/9Cpa7sJPMeFXzZ3gPSCiS9KhonRfCPjr8mpZsiCBcjZote55qSKRuz6gZ3ZioB2ReaeJ//COCWDY/QwAQpZSpEYHDGL79sw8P8oZnQylQKpbYLXATVQUhqbhmYiZDIfWlLjqNX/Koy2NA6Bc3i35qojPco9bHC/b7D6sv/BkovqOBRLzJZSV1N+Tkf5RqbPiiwj14GRwN4Nr69HYvhwFcvfK+8BGbQr6kaNulmeeK7s6lY+Q8qInZq01qtsCv++A6vYRSJDVk2nmnqYRfFzaS5sD3o8kZZoGefryz7TM7j1SRPboipygvvOO/7IKAzG9vtQl,iv:T0GkZKj959OIDhoXbqL7G0o9VBXvdSPYdgTOQ6411Ok=,tag:zg+rEcG91s2rZ6EIirunNw==,type:str]
restic: ENC[AES256_GCM,data:n8WzvSWUPGTO+8083O6E+PAuvT/+JevOHuN6+0d8ehA9x1E3pqeyQb6tuSr7pProuEQ9RR5BanYcL7o4z3mC3p+dmxAxYu7znr1pLbxLJiA=,iv:cOQd+UpZhIoBIAwiYvQ0qv5JeLucapnilyTRdiJR3uk=,tag:bH/JGMj6fOiMoJohZ2YDxw==,type:str]
sops:
    age:
        - recipient: age1a82mdpvl5w2j0ahyccngc2wvwgrhezrnwn5te99yxy254f9nm54qex3r0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkxtYzhZcXlZcWJnOVhv
            blZ2VFZSSm5pRHJyd0pydGZVV1lXU2VIa0U0Ck9GV0gwSi91R2VvcVNOb1R0blJR
            ZWh5L0lVTTk2WW1SRlNHY3ZOcDR4VDgKLS0tIDFucDJCUVNUZGhyd2d5UmRuSkJq
            RmxzeUVJSEZGQ25jMEY1NVJiQXNRYVEKxkdJ/aceQHLb/gTQeHDPFbnvUqcxSLu6
            fbkm0Z0HArtF9sTLSwGAYsF2V2OOQYOoz7mJ1qaSq2q76kOF6o1yMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVJGcDRQQXJJYTI1cU05
            aHcwZ0JkMk5iR2dYZ08zY0R2WGNjcXZrSDFFClhOK0s4b1puV2FxK3JnZWgwZ2dI
            ZU1nNlBabld0MEdreEVEVTl4KzlZbzQKLS0tIFNuN3NId2xwSzZsN0J3Y1VJd2k1
            K0c4UlZoTWtRTzVUK2VIVmpKZm1rbTgK3Dlnoiri6lalzi2n9hL46szzebiMpkbv
            yII1wWTjJQtH5+6uMp/9hr/cOzf9R4U85DSgyDp5na02g4j33/W+CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T20:05:36Z"
    mac: ENC[AES256_GCM,data:a5due/GIJzrw+el90DEzm6f6Ja/oVL4f/F7Rq4yz19pY+3f+g0D8WFdxLlRtOq+m1Otvwj1qHOeX/3DK14mhkmHIYNgFYTsFOXE/NdXIFjU8aZ+wwsa958uQL0tA6cA/75LQsWdm5/wnAIJC+6/ousP9TgkWge3t+WAl2B+ARhc=,iv:cFmAHud2c5hyz74p2pKQl20O7ECaYnKb8mDumnaTok4=,tag:mTRBJgr3Qea3qIwDLeHk3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
