placeholder: ENC[AES256_GCM,data:lCW2u0M+nl6kPO8=,iv:x/Sqb0NLmvDWCnFXeBTuosm20q835zcl67itgjjFDc4=,tag:UMViTGY7wVOeIIk4yNbiqQ==,type:str]
sops:
    age:
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdVpJdnBhT2xmdyt3WVRQ
            MHNKcEJTczhRdWhoeUJoNDZrc0krNnd0NldzCmpnTEt4VzdiZ1NpQ3RUYWJIV1Uv
            cUpNSFFsRFl1cmFlVytwTlRNSHdNN0EKLS0tIHlTVTNiZkFxS0hsdVlWUHNsaEhW
            eFE4Z0VVRWZqTzVrNDBIaHpLYVlrUUEKm6PGltjklLC/p3qPn2BNNN0//xcp5nLJ
            3uZvCcD2Jw2KuszJedcANUve8h+NXOS0ovFycmS4oy6niVBf2JAN1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T14:43:30Z"
    mac: ENC[AES256_GCM,data:TVC4luJJzfx6ecRzrc4+kGTuB/FvNCd7XfCnag5RwyNyFVF5cYBcvrGCl8GioNoe2cVvqXHhSTkPxdCOohBwitoB9+4WghxyphzdezRLIWpXqeoUWmBxOep9/yGI9l1Hd4yY7PXiBRXQk7RK+Uu0idYiXSPWkAd/4BqFaQC9UL4=,iv:wU4lMLBDHxw/5tFKTOxSYGUX5EitmDD3YoFYCA5IFFI=,tag:fQ4Hi3o3fXfgeVVxISxQgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
